//=========================================================================

window.raudrohi.widgets.g1.optionaldate_t1 =
function (s_html_id, parent_instance, s_menuitem_text_if_date_is_not_set,
    s_menuitem_text_if_date_is_set, s_display_format, s_language, s_mode) {
    try {
        s_display_format = typeof(s_display_format) !==
                           'undefined' ? s_display_format : 'DD/MM/YY';
        s_language = typeof(s_language) !== 'undefined' ? s_language : 'uk';
        s_mode = typeof(s_mode) !== 'undefined' ? s_mode : 'vertical_1';

        var s_display_format_ = s_display_format;
        var s_language_ = s_language;
        var s_menuitem_text_if_date_is_not_set_ = s_menuitem_text_if_date_is_not_set;
        var s_menuitem_text_if_date_is_set_ = s_menuitem_text_if_date_is_set;
        var s_mode_ = s_mode;

        // RENESSAATOR_BLOCK_START
// RENESSAATOR_BLOCK_ID=block_1
// RENESSAATOR_SOURCE_LANGUAGE=Ruby
// RENESSAATOR_SOURCE_START
// RAUDROHI_HOME=ENV['RAUDROHI_HOME']
// require(RAUDROHI_HOME+"/src/dev_tools/code_generation/raudrohi_cg0.rb")
// require(RAUDROHI_CODE_GENERATION+"/by_file/raudrohi_js_widgets_optionaldate_t1_block_1.rb")
// RENESSAATOR_SOURCE_END
//
// RENESSAATOR_AUTOGENERATED_TEXT_START
    if(raudrohi_settings_debug_JavaScript===true){
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_debug_verification 
            window.raudrohi.base.assert_is_HTML_ID(s_html_id,'s_html_id',
                '7247831f-f47b-45b1-8b7f-00b360409dd7');
window.raudrohi.base.assert_is_g1_widget(parent_instance,'parent_instance',
                '9290068b-6585-431d-b8ef-00b360409dd7');
window.raudrohi.base.assert_isString(s_mode,'s_mode',
                '4ff59fe4-5e70-4004-844f-00b360409dd7');
window.raudrohi.base.assert_isString(s_display_format,'s_display_format',
                '8302e67a-65b7-45ba-9930-00b360409dd7');
window.raudrohi.base.assert_isString(s_language,'s_language',
                '2ca161f2-bc42-444e-ab30-00b360409dd7');

    } // if

    if(raudrohi_settings_debug_JavaScript===true){
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_debug_verification 
            window.raudrohi.base.assert_is_HTML_ID(s_html_id,'s_html_id',
                '4daa7f75-7bb8-4389-a310-00b360409dd7');
window.raudrohi.base.assert_is_g1_widget(parent_instance,'parent_instance',
                '170d1594-7749-46e7-bb50-00b360409dd7');

    } // if
     //---widget--boilerplate_1_--start--
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_widget 
		var self_public_=this;
		var pileofmethods_t1_=new window.raudrohi.widgets.g1.pileofmethods_t1(
                 self_public_,'window.raudrohi.widgets.g1.optionaldate_t1',
                 s_html_id);
		var prc_=self_public_.private_code_;
		var wg_hooks_=self_public_.wg_hooks_;
     //---widget--boilerplate_1_--end----


prc_.parent_instance_=parent_instance;

var widget_calendar_t1_datewg_=null;
var id_calendar_t1_datewg_=prc_.html_id_+'_calendar_t1_datewg';
var widget_partialmenu_t1_date_set_=null;
var id_partialmenu_t1_date_set_=prc_.html_id_+'_partialmenu_t1_date_set';



   		function create_widgets_autogen( ){
				        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_widget 
			try{
				widget_calendar_t1_datewg_=new window.raudrohi.widgets.g1.calendar_t1(id_calendar_t1_datewg_,
self_public_,s_display_format_,s_language_);
widget_calendar_t1_datewg_.s_field_name_in_parent='datewg';
prc_.register_subwidget(
widget_calendar_t1_datewg_,'hidden');

widget_partialmenu_t1_date_set_=new
        window.raudrohi.widgets.g1.partialmenu_t1(
                id_partialmenu_t1_date_set_,self_public_,
                i_menu_max_width_,5,1,
                'There is a bug, menu content not set.',
                'partialmenu_t1_mode_1','partialmenu_t1_containertype_vertical_1');
widget_partialmenu_t1_date_set_.s_field_name_in_parent='date_set';
prc_.register_subwidget(
        widget_partialmenu_t1_date_set_,'visible');

var ar_autogenerated_tmpvar_45a99338_a5d6_49fd_9133_00b360409dd7=[];
var x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7;
x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7={};
x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7.s_label1='f';
x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7.s_label2=s_menuitem_text_if_date_is_not_set_;
ar_autogenerated_tmpvar_45a99338_a5d6_49fd_9133_00b360409dd7.push(x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7);
x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7={};
x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7.s_label1='t';
x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7.s_label2=s_menuitem_text_if_date_is_set_;
ar_autogenerated_tmpvar_45a99338_a5d6_49fd_9133_00b360409dd7.push(x_autogenerated_tmpvar_cc54a6c2_4fcb_4abe_b113_00b360409dd7);

widget_partialmenu_t1_date_set_.set_menu_content(ar_autogenerated_tmpvar_45a99338_a5d6_49fd_9133_00b360409dd7)
widget_partialmenu_t1_date_set_.set_default_value_for_the_menu('f');
			} catch(err){
				window.raudrohi.tmg('57610072-7fd0-47e1-9513-00b360409dd7',err);
			} // catch
		} // create_widgets_autogen


// RENESSAATOR_AUTOGENERATED_TEXT_END
// RENESSAATOR_BLOCK_END

        var lc_s_content = "content";
        var i_menu_max_width_ = s_menuitem_text_if_date_is_not_set_.length;
        if (i_menu_max_width_ < s_menuitem_text_if_date_is_set_.length) {
            i_menu_max_width_ = s_menuitem_text_if_date_is_set_.length;
        } // if

        if (raudrohi_settings_debug_JavaScript === true) {
            switch (s_mode_) {
                case 'vertical_1':
                    break;
                case 'horizontal_1':
                    break;
                default:
                    if (raudrohi_settings_debug_JavaScript) {
                        throw window.raudrohi.tmg(
                            '9d6f5710-eda4-4368-8509-211350705dd7',
                            'There\'s no branching for s_mode_(==' +
                            s_mode_ + ').');
                    } // if
            } // switch
        } // if

        prc_.content_ = {};
        prc_.content_.b_date_determined = false;
        prc_.content_.s_date_unix_time = "1";

        var ht_containers_html_cache_ = new Hashtable();

        function create_containers() {
            try {
                var s_containers = null;
                if (prc_.containers_html_cached_ !== true) {
                    var s = null;

                    // raudrohi_positioning_table, raudrohi_visible_table
                    var ar_class_names = ["raudrohi_positioning_table"];

                    s = '' +
                        '<tr>' + "\n" + '<td id="' +
                        id_partialmenu_t1_date_set_ +
                        '_div"></td>' + "\n" + '<tr>' + "\n" +
                        '<tr>' + "\n" + '<td id="' + id_calendar_t1_datewg_ +
                        '_div"></td>' + "\n" + '<tr>' + "\n" +
                        '';
                    s_containers = prc_.selfread.wrap_2_alignment_div(
                        window.raudrohi.lang.cg_table_t1(s, ar_class_names));
                    ht_containers_html_cache_.put("vertical_1", s_containers);

                    s = '' +
                        '<tr><td id="' + id_partialmenu_t1_date_set_ +
                        '_div"></td>' +
                        '<td id="' + id_calendar_t1_datewg_ +
                        '_div"></td><tr>' + "\n" +
                        '';
                    s_containers = prc_.selfread.wrap_2_alignment_div(
                        window.raudrohi.lang.cg_table_t1(s, ar_class_names));
                    ht_containers_html_cache_.put("horizontal_1", s_containers);

                    prc_.containers_html_cached_ = true;
                } // if
                s_containers = ht_containers_html_cache_.get(s_mode_);
                window.raudrohi.base.set_innerHTML(prc_.container_id_, s_containers);
            } catch (err) {
                window.raudrohi.tmg('940aa44e-054a-4e47-a309-211350705dd7',
                    "s_mode_==" + s_mode + "  " + err);
            } // catch
        } // create_containers

        function update_calendar_widget_visibility() {
            try {
                if (prc_.content_.b_date_determined === true) {
                    prc_.mark_elemwidget_to_be_unhidden(
                        widget_calendar_t1_datewg_);
                } else {
                    prc_.mark_elemwidget_to_be_hidden(
                        widget_calendar_t1_datewg_, true);
                } // else
            } catch (err) {
                window.raudrohi.tmg('52098061-6424-45ad-ba09-211350705dd7', err);
            } // catch
        } // update_calendar_widget_visibility


        prc_.customizable.compulsory.render_editable = function () {
            try {
                create_containers();
                prc_.mark_elemwidget_to_be_unhidden(
                    widget_partialmenu_t1_date_set_);
                update_calendar_widget_visibility();
            } catch (err) {
                window.raudrohi.tmg('7114c554-3199-4098-8409-211350705dd7', err);
            } // catch
        } // prc_.customizable.compulsory.render_editable

        prc_.customizable.compulsory.render_readonly = function () {
            try {
                create_containers();
                if (prc_.content_.b_date_determined === true) {
                    prc_.mark_elemwidget_to_be_hidden(
                        widget_partialmenu_t1_date_set_, true);
                } else {
                    prc_.mark_elemwidget_to_be_unhidden(
                        widget_partialmenu_t1_date_set_);
                } // else
                update_calendar_widget_visibility();
            } catch (err) {
                window.raudrohi.tmg('2e8af853-2866-4758-9309-211350705dd7', err);
            } // catch
        } // prc_.customizable.compulsory.render_readonly

        function evh_optionaldate_t1_menuselection(mi) {
            try {
                if (mi.s_label1 === 't') {
                    if (prc_.content_.b_date_determined === true) {
                        return;
                    } // if
                    prc_.content_.b_date_determined = true;
                } else {
                    if (prc_.content_.b_date_determined === false) {
                        return;
                    } // if
                    prc_.content_.b_date_determined = false;
                } // else
                prc_.repaint_if_graphical_and_not_hidden();
            } catch (err) {
                window.raudrohi.tmg('94b5cdf4-93f2-40c5-a109-211350705dd7', err);
            } // catch
        } // evh_optionaldate_t1_menuselection


        prc_.customizable.optional.create_subwidgets = function () {
            try {
                create_widgets_autogen();
                widget_partialmenu_t1_date_set_.private_code_.customizable.optional.evh_selection_impl =
                evh_optionaldate_t1_menuselection;
                self_public_.set_content_2_default();
            } catch (err) {
                window.raudrohi.tmg('74a2a337-bfce-4f13-9509-211350705dd7', err);
            } // catch
        } // create_widgets

        // A state, where the date is not determined, is
        // actually one of the this widget's content values.
        // So, even, if the date is not determined, the content
        // of this widget is still set.
        function set_state_to_date_not_determined() {
            try {
                prc_.content_.b_date_determined = false;
                widget_partialmenu_t1_date_set_.set_content_by_s_label1('f');
                prc_.repaint_if_graphical_and_not_hidden();
                widget_calendar_t1_datewg_.set_content_2_now();
            } catch (err) {
                window.raudrohi.tmg('e2219743-fae7-4501-a4f8-211350705dd7', err);
            } // catch
        } // set_state_to_date_not_determined

        // The content of this widget is always set.
        this.set_content_2_default = function () {
            try {
                set_state_to_date_not_determined();
                prc_.content_set_ = true;
            } catch (err) {
                window.raudrohi.tmg('89f15c29-4737-4a8a-81f8-211350705dd7', err);
            } // catch
        } // set_content_2_default

        // Returns null or a string that represents
        // unix time in seconds.
        this.get_content = function () {
            try {
                var x_out = null;
                if (prc_.content_.b_date_determined === true) {
                    x_out = widget_calendar_t1_datewg_.get_content_unix_time();
                } // if
                return x_out;
            } catch (err) {
                window.raudrohi.tmg('5f36da10-3df6-498b-b2f8-211350705dd7', err);
            } // catch
        } // get_content

        this.set_content = function (s_unix_time_in_seconds_or_null) {
            try {
                if (raudrohi_settings_debug_JavaScript === true) {
                    if (s_unix_time_in_seconds_or_null !== null) {
                        window.raudrohi.base.assert_isString(
                            s_unix_time_in_seconds_or_null,
                            's_unix_time_in_seconds_or_null',
                            'cdfcf23f-2e81-4f35-94f8-211350705dd7');
                    } // if
                } // if
                if (s_unix_time_in_seconds_or_null === null) {
                    set_state_to_date_not_determined();
                } else {
                    prc_.content_.b_date_determined = true;
                    widget_partialmenu_t1_date_set_.set_content_by_s_label1('t');
                    widget_calendar_t1_datewg_.set_content_by_unix_time(
                        s_unix_time_in_seconds_or_null);
                } // else
                prc_.repaint_if_graphical_and_not_hidden();
            } catch (err) {
                window.raudrohi.tmg('353e851b-58e4-4250-82f8-211350705dd7', err);
            } // catch
        } // set_content


        this.get_content_2_collection_t1 = function (ht) {
            try {
                if (raudrohi_settings_debug_JavaScript === true) {
                    window.raudrohi.base.assert_isObject(ht, 'ht',
                        'a5403215-ccbd-4a43-91f8-211350705dd7');
                } // if
                var s_unix_time = self_public_.get_content();
                if (s_unix_time === null) { //== <field not set>
                    s_unix_time = "";
                } // if
                window.raudrohi.wg_processing_t1.dbfcreate_s_t1(ht,
                    "i_" + self_public_.s_field_name_in_parent + "_unix_time",
                    s_unix_time, false);
            } catch (err) {
                window.raudrohi.tmg('61b5313a-8bd6-4523-95f8-211350705dd7', err);
            } // catch
        } // get_content_2_collection_t1

        this.set_content_from_collection_t1 = function (ht) {
            try {
                var s_key_subfield_set = "dbf_sb_i_" +
                                         self_public_.s_field_name_in_parent +
                                         "_unix_time_set";
                var s_key_field = "dbf_i_" +
                                  self_public_.s_field_name_in_parent +
                                  "_unix_time";

                if (raudrohi_settings_debug_JavaScript === true) {
                    window.raudrohi.base.assert_isObject(ht, 'ht',
                        'cc1b2b41-4929-48b7-b4f8-211350705dd7');
                    if (ht.containsKey(s_key_subfield_set) !== true) {
                        window.raudrohi.tmg('bb023341-766c-4567-a1f8-211350705dd7',
                            'The ht does not contain the key "' +
                            s_key_subfield_set + '".');
                    } // if
                    if (ht.containsKey(s_key_field) !== true) {
                        window.raudrohi.tmg('f1b0c1f9-e0d8-4079-a5f8-211350705dd7',
                            'The ht does not contain the key "' +
                            s_key_field + '".');
                    } // if
                } // if
                var s_unix_time = null;
                if (ht.get(s_key_subfield_set) === 't') {
                    s_unix_time = ht.get(s_key_field);
                } // if
                self_public_.set_content(s_unix_time);
            } catch (err) {
                window.raudrohi.tmg('7843381a-98f5-406a-95e8-211350705dd7', err);
            } // catch
        } // set_content_from_collection_t1


        self_public_.startup_sequence_init();

    } catch (err) {
        window.raudrohi.tmg('05457150-75f8-4670-83e8-211350705dd7', err);
    } // catch
} // window.raudrohi.widgets.g1.optionaldate_t1

//------------------------------------------------------------------------
