//=========================================================================

raudrohi.widgets.g1.optionaldate_t1=function(s_html_id,parent_instance,
	s_menuitem_text_if_date_is_not_set,s_menuitem_text_if_date_is_set,
	s_display_format,s_language,s_mode){
	try{
		s_display_format = typeof(s_display_format) !== 'undefined' ? s_display_format : 'DD/MM/YY';
		s_language = typeof(s_language) !== 'undefined' ? s_language : 'uk';
		s_mode = typeof(s_mode) !== 'undefined' ? s_mode : 'vertical_1';

		var s_display_format_=s_display_format;
		var s_language_=s_language;
		var s_menuitem_text_if_date_is_not_set_=s_menuitem_text_if_date_is_not_set;
		var s_menuitem_text_if_date_is_set_=s_menuitem_text_if_date_is_set;
		var s_mode_=s_mode;

		// RENESSAATOR_BLOCK_START
// RENESSAATOR_BLOCK_ID=block_1
// RENESSAATOR_SOURCE_LANGUAGE=Ruby
// RENESSAATOR_SOURCE_START
// RAUDROHI_HOME=ENV['RAUDROHI_HOME']
// require(RAUDROHI_HOME+"/src/dev_tools/code_generation/raudrohi_cg0.rb")
// require(RAUDROHI_CODE_GENERATION+"/by_file/raudrohi_js_widgets_optionaldate_t1_block_1.rb")
// RENESSAATOR_SOURCE_END
//
// RENESSAATOR_AUTOGENERATED_TEXT_START
    if(raudrohi_settings_debug_JavaScript===true){
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_debug_verification 
            raudrohi.base.assert_isString(s_mode,'s_mode',
                '59d5b023-dfe7-48fa-a389-02f1d0a04dd7');
raudrohi.base.assert_isString(s_display_format,'s_display_format',
                '3fd6dd28-396d-4b93-a489-02f1d0a04dd7');
raudrohi.base.assert_isString(s_language,'s_language',
                '3268e627-6b98-48e2-b489-02f1d0a04dd7');

    } // if

    if(raudrohi_settings_debug_JavaScript===true){
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_debug_verification 
            raudrohi.base.assert_isString(s_html_id,'s_html_id',
                '3abcaed1-5984-4cdd-9199-02f1d0a04dd7');
raudrohi.base.assert_isObject(parent_instance,'parent_instance',
                '0fc72533-11a9-4411-b299-02f1d0a04dd7');

    } // if
     //---widget--boilerplate_1_--start--
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_widget 
		var self_public_=this;
		var pileofmethods_t1_=new raudrohi.widgets.g1.pileofmethods_t1(
                 self_public_,'raudrohi.widgets.g1.optionaldate_t1',
                 s_html_id);
		var prc_=self_public_.private_code_;
		var wg_hooks_=self_public_.wg_hooks_;
     //---widget--boilerplate_1_--end----


prc_.parent_instance_=parent_instance;

var widget_calendar_t1_datewg_=null;
var id_calendar_t1_datewg_=prc_.html_id_+'_calendar_t1_datewg';
var widget_partialmenu_t1_date_set_=null;
var id_partialmenu_t1_date_set_=prc_.html_id_+'_partialmenu_t1_date_set';



   		function create_widgets_autogen( ){
				        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_widget 
			try{
				widget_calendar_t1_datewg_=new raudrohi.widgets.g1.calendar_t1(id_calendar_t1_datewg_,
self_public_,s_display_format_,s_language_);
widget_calendar_t1_datewg_.s_field_name_in_parent='datewg';
prc_.register_subwidget(
widget_calendar_t1_datewg_,'hidden');

widget_partialmenu_t1_date_set_=new
        raudrohi.widgets.g1.partialmenu_t1(
                id_partialmenu_t1_date_set_,self_public_,
                i_menu_max_width_,5,1,
                'There is a bug, menu content not set.',
                'partialmenu_t1_mode_1','partialmenu_t1_containertype_vertical_1');
widget_partialmenu_t1_date_set_.s_field_name_in_parent='date_set';
prc_.register_subwidget(
        widget_partialmenu_t1_date_set_,'visible');

var ar_autogenerated_tmpvar_aee94634_05f6_4dda_93b9_02f1d0a04dd7=[];
var x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7;
x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7={};
x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7.s_label1='f';
x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7.s_label2=s_menuitem_text_if_date_is_not_set_;
ar_autogenerated_tmpvar_aee94634_05f6_4dda_93b9_02f1d0a04dd7.push(x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7);
x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7={};
x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7.s_label1='t';
x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7.s_label2=s_menuitem_text_if_date_is_set_;
ar_autogenerated_tmpvar_aee94634_05f6_4dda_93b9_02f1d0a04dd7.push(x_autogenerated_tmpvar_2840cd02_24a2_44ca_94b9_02f1d0a04dd7);

widget_partialmenu_t1_date_set_.set_menu_content(ar_autogenerated_tmpvar_aee94634_05f6_4dda_93b9_02f1d0a04dd7)
widget_partialmenu_t1_date_set_.set_default_value_for_the_menu('f');
			} catch(err){
				raudrohi.tmg('98d6f610-16b6-4c01-81c9-02f1d0a04dd7',err);
			} // catch
		} // create_widgets_autogen


// RENESSAATOR_AUTOGENERATED_TEXT_END
// RENESSAATOR_BLOCK_END

		var lc_s_content="content";
		var i_menu_max_width_=s_menuitem_text_if_date_is_not_set_.length;
		if(i_menu_max_width_<s_menuitem_text_if_date_is_set_.length){
			i_menu_max_width_=s_menuitem_text_if_date_is_set_.length;
		} // if

		if(raudrohi_settings_debug_JavaScript===true){
			switch(s_mode_){
				case 'vertical_1':
					break;
				case 'horizontal_1':
					break;
				default:
					if(raudrohi_settings_debug_JavaScript){
						throw raudrohi.tmg(
							'3251d044-0d5e-49bb-883d-4170a0219bd7',
							'There\'s no branching for s_mode_(=='+
							s_mode_+').');
					} // if
			} // switch
		} // if

		prc_.content_={};
		prc_.content_.b_date_determined=false;
		prc_.content_.s_date_unix_time="1";

		var ht_containers_html_cache_=new Hashtable();
		function create_containers(){
			try{
				var s_containers=null;
				if(prc_.containers_html_cached_!==true){
					var s=null;

					// raudrohi_positioning_table, raudrohi_visible_table
					var ar_class_names=["raudrohi_positioning_table"];

					s=''+
					'<tr>'+"\n"+'<td id="'+id_partialmenu_t1_date_set_+
					'_div"></td>'+"\n"+'<tr>'+"\n"+
					'<tr>'+"\n"+'<td id="'+id_calendar_t1_datewg_+
					'_div"></td>'+"\n"+'<tr>'+"\n"+
					'';
					s_containers=prc_.selfread.wrap_2_alignment_div(
						raudrohi.lang.cg_table_t1(s,ar_class_names));
					ht_containers_html_cache_.put("vertical_1",s_containers);

					s=''+
					'<tr><td id="'+id_partialmenu_t1_date_set_+
					'_div"></td>'+
					'<td id="'+id_calendar_t1_datewg_+
					'_div"></td><tr>'+"\n"+
					'';
					s_containers=prc_.selfread.wrap_2_alignment_div(
						raudrohi.lang.cg_table_t1(s,ar_class_names));
					ht_containers_html_cache_.put("horizontal_1",s_containers);

					prc_.containers_html_cached_=true;
				} // if
				s_containers=ht_containers_html_cache_.get(s_mode_);
				raudrohi.base.set_innerHTML(prc_.container_id_,s_containers);
			} catch (err){
				raudrohi.tmg('27edde28-e698-4e4c-b43d-4170a0219bd7',
					"s_mode_=="+s_mode+"  "+err);
			} // catch
		} // create_containers

		function update_calendar_widget_visibility(){
			try{
				if(prc_.content_.b_date_determined===true){
					prc_.mark_elemwidget_to_be_unhidden(
						widget_calendar_t1_datewg_);
				} else {
					prc_.mark_elemwidget_to_be_hidden(
						widget_calendar_t1_datewg_,true);
				} // else
			} catch (err){
				raudrohi.tmg('42d962d1-080b-4e88-a43d-4170a0219bd7',err);
			} // catch
		} // update_calendar_widget_visibility


		prc_.customizable.compulsory.render_editable=function(){
			try{
				create_containers();
				prc_.mark_elemwidget_to_be_unhidden(
					widget_partialmenu_t1_date_set_);
				update_calendar_widget_visibility();
			} catch (err){
				raudrohi.tmg('58ddca32-981b-419a-823d-4170a0219bd7',err);
			} // catch
		} // prc_.customizable.compulsory.render_editable

		prc_.customizable.compulsory.render_readonly=function(){
			try{
				create_containers();
				if(prc_.content_.b_date_determined===true){
					prc_.mark_elemwidget_to_be_hidden(
						widget_partialmenu_t1_date_set_,true);
				} else {
					prc_.mark_elemwidget_to_be_unhidden(
						widget_partialmenu_t1_date_set_);
				} // else
				update_calendar_widget_visibility();
			} catch (err){
				raudrohi.tmg('422da2c5-2572-4a46-943d-4170a0219bd7',err);
			} // catch
		} // prc_.customizable.compulsory.render_readonly

		function evh_optionaldate_t1_menuselection(mi){
			try{
				if(mi.s_label1==='t'){
					if(prc_.content_.b_date_determined===true){
						return;
					} // if
					prc_.content_.b_date_determined=true;
				} else {
					if(prc_.content_.b_date_determined===false){
						return;
					} // if
					prc_.content_.b_date_determined=false;
				} // else
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('92011444-e060-43ef-a23d-4170a0219bd7',err);
			} // catch
		} // evh_optionaldate_t1_menuselection


		prc_.customizable.optional.create_subwidgets=function(){
			try{
				create_widgets_autogen();
				widget_partialmenu_t1_date_set_.private_code_.customizable.optional.evh_selection_impl=evh_optionaldate_t1_menuselection;
				self_public_.set_content_2_default();
			} catch (err){
				raudrohi.tmg('cbd4552a-4dba-4ee1-b13d-4170a0219bd7',err);
			} // catch
		} // create_widgets

		// A state, where the date is not determined, is
		// actually one of the this widget's content values.
		// So, even, if the date is not determined, the content
		// of this widget is still set.
		function set_state_to_date_not_determined(){
			try{
				prc_.content_.b_date_determined=false;
				widget_partialmenu_t1_date_set_.set_content_by_s_label1('f');
				prc_.repaint_if_graphical_and_not_hidden();
				widget_calendar_t1_datewg_.set_content_2_now();
			} catch (err){
				raudrohi.tmg('11bb2681-ee90-4613-af3d-4170a0219bd7',err);
			} // catch
		} // set_state_to_date_not_determined

		// The content of this widget is always set.
		this.set_content_2_default=function(){
			try{
				set_state_to_date_not_determined();
				prc_.content_set_=true;
			} catch (err){
				raudrohi.tmg('2d82022a-f504-4b50-b43d-4170a0219bd7',err);
			} // catch
		} // set_content_2_default

		// Returns null or a string that represents
		// unix time in seconds.
		this.get_content = function() {
			try {
				var x_out=null;
				if(prc_.content_.b_date_determined===true){
					x_out=widget_calendar_t1_datewg_.get_content_unix_time();
				} // if
				return x_out;
			} catch(err) {
				raudrohi.tmg('277550e5-36cf-4a24-a23d-4170a0219bd7', err);
			} // catch
		} // get_content

		this.set_content = function(s_unix_time_in_seconds_or_null) {
			try {
				if(raudrohi_settings_debug_JavaScript===true){
					if(s_unix_time_in_seconds_or_null!==null){
						raudrohi.base.assert_isString(
							s_unix_time_in_seconds_or_null,
							's_unix_time_in_seconds_or_null',
							'b9b1233f-6d45-4170-b53d-4170a0219bd7');
					} // if
				} // if
				if(s_unix_time_in_seconds_or_null===null){
					set_state_to_date_not_determined();
				} else {
					prc_.content_.b_date_determined=true;
					widget_partialmenu_t1_date_set_.set_content_by_s_label1('t');
					widget_calendar_t1_datewg_.set_content_by_unix_time(
						s_unix_time_in_seconds_or_null);
				} // else
				prc_.repaint_if_graphical_and_not_hidden();
			} catch(err) {
				raudrohi.tmg('3784bac2-4981-42d8-953d-4170a0219bd7', err);
			} // catch
		} // set_content


		this.get_content_2_collection_t1=function(ht){
			try{
				if(raudrohi_settings_debug_JavaScript===true){
					raudrohi.base.assert_isObject(ht,'ht',
						'4ebd975b-f126-4b1b-a13d-4170a0219bd7');
				} // if
				var s_unix_time=self_public_.get_content();
				if(s_unix_time===null){ //== <field not set>
					s_unix_time="";
				} // if
				raudrohi.wg_processing_t1.dbfcreate_s_t1(ht,
					"i_"+self_public_.s_field_name_in_parent+"_unix_time",
					s_unix_time,false);
			} catch (err){
				raudrohi.tmg('a94e012d-cac1-4463-832d-4170a0219bd7',err);
			} // catch
		} // get_content_2_collection_t1

		this.set_content_from_collection_t1=function(ht){
			try{
				var s_key_subfield_set="dbf_sb_i_"+
				self_public_.s_field_name_in_parent+"_unix_time_set";
				var s_key_field="dbf_i_"+
				self_public_.s_field_name_in_parent+"_unix_time";

				if(raudrohi_settings_debug_JavaScript===true){
					raudrohi.base.assert_isObject(ht,'ht',
						'15e3c655-2650-45ff-922d-4170a0219bd7');
					if(ht.containsKey(s_key_subfield_set)!==true){
						raudrohi.tmg('17a8c1ad-e558-4647-852d-4170a0219bd7',
							'The ht does not contain the key "'+
							s_key_subfield_set+'".');
					} // if
					if(ht.containsKey(s_key_field)!==true){
						raudrohi.tmg('43d6972e-2af4-4a9a-822d-4170a0219bd7',
							'The ht does not contain the key "'+
							s_key_field+'".');
					} // if
				} // if
				var s_unix_time=null;
				if(ht.get(s_key_subfield_set)==='t'){
					s_unix_time=ht.get(s_key_field);
				} // if
				self_public_.set_content(s_unix_time);
			} catch (err){
				raudrohi.tmg('183b9079-17b4-4c08-b12d-4170a0219bd7',err);
			} // catch
		} // set_content_from_collection_t1


		self_public_.startup_sequence_init();

	} catch (err){
		raudrohi.tmg('e2d37353-cd45-4b8d-a12d-4170a0219bd7',err);
	} // catch
} // raudrohi.widgets.g1.optionaldate_t1

//------------------------------------------------------------------------
