//=========================================================================
// Copyright (c) 2011, martin.vahi@softf1.com that has an
// Estonian personal identification code of 38108050020.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or
// without modification, are permitted provided that the following
// conditions are met:
//
// * Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer
//   in the documentation and/or other materials provided with the
//   distribution.
// * Neither the name of the Martin Vahi nor the names of its
//   contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
// CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//=========================================================================

// It's instantiated in the library constructor.
raudrohi.widgets.g1.password_editor_t1=function(s_html_id,parent_instance){
	try{

		// RENESSAATOR_BLOCK_START
		// RENESSAATOR_BLOCK_ID=block_1
		// RENESSAATOR_SOURCE_LANGUAGE=Ruby
		// RENESSAATOR_SOURCE_START
		// RAUDROHI_CODE_GENERATION=ENV['RAUDROHI_CODE_GENERATION']
		// require(RAUDROHI_CODE_GENERATION+"/by_file/raudrohi_js_widgets_password_editor_t1_block_1.rb")
		// RENESSAATOR_SOURCE_END
		//
		// RENESSAATOR_AUTOGENERATED_TEXT_START

		if(raudrohi.settings.debug_JavaScript===true){
			// WARNING: This function resides in an autogeneration region.
			// This code has been autogenerated by: Raudrohi_cg_debug_verification
			raudrohi.base.assert_isString(s_html_id,'s_html_id',
				'b01fa031-a5b2-4716-b432-10f25081abd7');
			raudrohi.base.assert_isObject(parent_instance,'parent_instance',
				'3d9b3053-5949-4dcd-b432-10f25081abd7');

		} // if
		//---widget--boilerplate_1_--start--
		// WARNING: This function resides in an autogeneration region.
		// This code has been autogenerated by: Raudrohi_cg_widget
		var self_public_=this;
		var pileofmethods_t1_=new raudrohi.widgets.g1.pileofmethods_t1(
			self_public_,'raudrohi.widgets.g1.password_editor_t1',
			s_html_id);
		var prc_=self_public_.private_code_;
		var wg_hooks_=self_public_.wg_hooks_;
		//---widget--boilerplate_1_--end----


		prc_.parent_instance_=parent_instance;

		var widget_partialmenu_t1_retain_or_modify_=null;
		var id_partialmenu_t1_retain_or_modify_=prc_.html_id_+'_partialmenu_t1_retain_or_modify';
		var widget_textarea_t1_line_1_=null;
		var id_textarea_t1_line_1_=prc_.html_id_+'_textarea_t1_line_1';
		var widget_textarea_t1_line_2_=null;
		var id_textarea_t1_line_2_=prc_.html_id_+'_textarea_t1_line_2';
		var widget_html_t2_line_1_legend_=null;
		var id_html_t2_line_1_legend_=prc_.html_id_+'_html_t2_line_1_legend';
		var widget_html_t2_line_2_legend_=null;
		var id_html_t2_line_2_legend_=prc_.html_id_+'_html_t2_line_2_legend';
		var widget_html_t2_disqualification_message_=null;
		var id_html_t2_disqualification_message_=prc_.html_id_+'_html_t2_disqualification_message';



		function create_widgets_autogen( ){
			// WARNING: This function resides in an autogeneration region.
			// This code has been autogenerated by: Raudrohi_cg_widget
			try{
				widget_partialmenu_t1_retain_or_modify_=new
				raudrohi.widgets.g1.partialmenu_t1(
					id_partialmenu_t1_retain_or_modify_,self_public_,
					40,40,1,
					"There is a flaw.  '21b15d4c-f968-49a2-a232-10f25081abd7'",
					'partialmenu_t1_mode_1','partialmenu_t1_containertype_vertical_1');
				widget_partialmenu_t1_retain_or_modify_.s_field_name_in_parent='retain_or_modify';
				prc_.register_subwidget(
					widget_partialmenu_t1_retain_or_modify_,'visible');

				var ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7=new Array();
				var x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7;
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7={};
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label1='retain';
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label2='Retain';
				ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7.push(x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7);
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7={};
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label1='modify';
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label2='Modify';
				ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7.push(x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7);

				widget_partialmenu_t1_retain_or_modify_.set_menu_content(ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7)
				var ht_widget_textarea_t1_line_1_params=raudrohi.base.pool_of_hashtables.get_empty_hashtable();
				ht_widget_textarea_t1_line_1_params.put('type','password');
				widget_textarea_t1_line_1_=new raudrohi.widgets.g1.textarea_t1(
					id_textarea_t1_line_1_,i_password_field_width_,1,
					ht_widget_textarea_t1_line_1_params);
				widget_textarea_t1_line_1_.set_alignment('west');
				prc_.register_subwidget(widget_textarea_t1_line_1_,'hidden');
				widget_textarea_t1_line_1_.s_field_name_in_parent='line_1';
				raudrohi.base.pool_of_hashtables.return_used_hashtable(ht_widget_textarea_t1_line_1_params);

				var ht_widget_textarea_t1_line_2_params=raudrohi.base.pool_of_hashtables.get_empty_hashtable();
				ht_widget_textarea_t1_line_2_params.put('type','password');
				widget_textarea_t1_line_2_=new raudrohi.widgets.g1.textarea_t1(
					id_textarea_t1_line_2_,i_password_field_width_,1,
					ht_widget_textarea_t1_line_2_params);
				widget_textarea_t1_line_2_.set_alignment('west');
				prc_.register_subwidget(widget_textarea_t1_line_2_,'hidden');
				widget_textarea_t1_line_2_.s_field_name_in_parent='line_2';
				raudrohi.base.pool_of_hashtables.return_used_hashtable(ht_widget_textarea_t1_line_2_params);

				widget_html_t2_line_1_legend_=new raudrohi.widgets.g1.html_t2(
					id_html_t2_line_1_legend_,self_public_);
				widget_html_t2_line_1_legend_.s_field_name_in_parent='line_1_legend';
				prc_.register_subwidget(
					widget_html_t2_line_1_legend_,'hidden');

				widget_html_t2_line_2_legend_=new raudrohi.widgets.g1.html_t2(
					id_html_t2_line_2_legend_,self_public_);
				widget_html_t2_line_2_legend_.s_field_name_in_parent='line_2_legend';
				prc_.register_subwidget(
					widget_html_t2_line_2_legend_,'hidden');

				widget_html_t2_disqualification_message_=new raudrohi.widgets.g1.html_t2(
					id_html_t2_disqualification_message_,self_public_);
				widget_html_t2_disqualification_message_.s_field_name_in_parent='disqualification_message';
				prc_.register_subwidget(
					widget_html_t2_disqualification_message_,'hidden');

			} catch(err){
				raudrohi.tmg('e4360b10-29dd-47b4-8532-10f25081abd7',err);
			} // catch
		} // create_widgets_autogen


		// RENESSAATOR_AUTOGENERATED_TEXT_END
		// RENESSAATOR_BLOCK_END
		//-----------------------------------------------------------------
		var s_create_containers_s_password_fields_table_='';
		var b_create_containers_s_password_fields_table_cached_=false;
		function create_containers_s_password_fields_table(){
			try{
				if(b_create_containers_s_password_fields_table_cached_!==true){
					var s_lines=''+
					'<tr>'+
					"\n"+
					'<td class="" colspan="1">'+
					'<div id="'+id_html_t2_line_1_legend_+'_div"></div></td>'+
					"\n"+
					'<td class="" colspan="1">'+
					'<div id="'+id_textarea_t1_line_1_+'_div"></div></td>'+
					"\n"+
					'</tr>'+
					'<tr>'+
					"\n"+
					'<td class="" colspan="1"></td>'+
					"\n"+
					'<td class="" colspan="1">'+
					'<div id="'+id_html_t2_disqualification_message_+'_div"></div></td>'+
					"\n"+
					'</tr>'+
					'<tr>'+
					"\n"+
					'<td class="" colspan="1">'+
					'<div id="'+id_html_t2_line_2_legend_+'_div"></div></td>'+
					"\n"+
					'<td class="" colspan="1">'+
					'<div id="'+id_textarea_t1_line_2_+'_div"></div></td>'+
					"\n"+
					'</tr>'+
					'';

					var ar_class_names=["raudrohi_positioning_table"]; // raudrohi_visible_table
					s_create_containers_s_password_fields_table_=raudrohi.lang.cg_table_t1(""+
						s_lines,
						ar_class_names);
					b_create_containers_s_password_fields_table_cached_=true;
				} // if
				var s_out=s_create_containers_s_password_fields_table_;
				return s_out;
			} catch (err){
				raudrohi.tmg('1cce2b7b-2ad1-450e-b232-10f25081abd7',err);
			} // catch
		} // create_containers_s_password_fields_table

		//-----------------------------------------------------------------
		function create_containers_s_lines_north(){
			try{
				var s_out=''+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1">'+
				'<div id="'+id_partialmenu_t1_retain_or_modify_+'_div"></div></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1">'+
				create_containers_s_password_fields_table()+
				'</td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'';
				return s_out;
			} catch (err){
				raudrohi.tmg('1c51d6e1-e36e-4aac-b122-10f25081abd7',err);
			} // catch
		} // create_containers_s_lines_north

		function create_containers_s_lines_south(){
			try{
				var s_out=''+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1">'+
				create_containers_s_password_fields_table()+
				'</td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1">'+
				'<div id="'+id_partialmenu_t1_retain_or_modify_+'_div"></div></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'';
				return s_out;
			} catch (err){
				raudrohi.tmg('13a1c49c-6e3c-4789-a322-10f25081abd7',err);
			} // catch
		} // create_containers_s_lines_south

		function create_containers_s_lines_east(){
			try{
				var s_out=''+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1">'+
				create_containers_s_password_fields_table()+
				'</td>'+
				"\n"+
				'<td class="" colspan="1">'+
				'<div id="'+id_partialmenu_t1_retain_or_modify_+'_div"></div></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'';
				return s_out;
			} catch (err){
				raudrohi.tmg('ff3e257d-481c-4ac0-9222-10f25081abd7',err);
			} // catch
		} // create_containers_s_lines_east

		function create_containers_s_lines_west(){
			try{
				var s_out=''+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1">'+
				'<div id="'+id_partialmenu_t1_retain_or_modify_+'_div"></div></td>'+
				"\n"+
				'<td class="" colspan="1">'+
				create_containers_s_password_fields_table()+
				'</td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'<tr>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'<td class="" colspan="1"></td>'+
				"\n"+
				'</tr>'+
				'';
				return s_out;
			} catch (err){
				raudrohi.tmg('decb224e-8b51-4b2d-9122-10f25081abd7',err);
			} // catch
		} // create_containers_s_lines_west

		function create_containers(){
			try{
				if(!prc_.containers_html_cached_){
					var s_lines=null;
					switch(s_menu_position_){
						case 'north':
							s_lines=create_containers_s_lines_north();
							break;
						case 'south':
							s_lines=create_containers_s_lines_south();
							break;
						case 'east':
							s_lines=create_containers_s_lines_east();
							break;
						case 'west':
							s_lines=create_containers_s_lines_west();
							break;
						default:
							if(raudrohi.settings.debug_JavaScript){
								throw raudrohi.tmg(
									'491dc54a-89a8-4256-a322-10f25081abd7',
									'There\'s no branching for s_menu_position(=='+
									s_menu_position_+').');
							} // if
					} // switch
					var ar_class_names=["raudrohi_positioning_table"]; // raudrohi_visible_table
					prc_.containers_html_cache_=raudrohi.lang.cg_table_t1(
						s_lines,ar_class_names);
					prc_.containers_html_cached_=true;
				} // if
				var s_container=prc_.containers_html_cache_;
				raudrohi.base.set_innerHTML(prc_.container_id_,s_container);
			} catch (err){
				raudrohi.tmg('3f63f82a-4cf0-46a7-8522-10f25081abd7',err);
			} // catch
		} // create_containers

		//-----------------------------------------------------------------
		//prc_.content_set_=false;
		var b_acceptable_password_string_available_=false;
		var b_password_string_available_but_unacceptable_=false;
		var s_acceptable_password_string_='';
		var s_password_rejection_message_='';

		function set_password_fields_table_visibility(b_true_if_visible){
			try{
				if(raudrohi.settings.debug_JavaScript===true){			
					raudrohi.base.assert_isBoolean(
						b_true_if_visible,'b_true_if_visible',
						'373d9c92-c67b-4569-9122-10f25081abd7');
				} // if                
				if(b_true_if_visible===true){
					if(b_password_string_available_but_unacceptable_===true){
						prc_.mark_elemwidget_to_be_unhidden(
							widget_html_t2_disqualification_message_);
					} else {
						prc_.mark_elemwidget_to_be_hidden(
							widget_html_t2_disqualification_message_,true);
					} // else
					prc_.mark_elemwidget_to_be_unhidden(
						widget_html_t2_line_1_legend_);
					prc_.mark_elemwidget_to_be_unhidden(
						widget_html_t2_line_2_legend_);
					prc_.mark_elemwidget_to_be_unhidden(
						widget_textarea_t1_line_1_);
					prc_.mark_elemwidget_to_be_unhidden(
						widget_textarea_t1_line_2_);
				} else { // hide it all
					prc_.mark_elemwidget_to_be_hidden(
						widget_html_t2_disqualification_message_,true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_html_t2_line_1_legend_,true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_html_t2_line_2_legend_,true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_textarea_t1_line_1_,true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_textarea_t1_line_2_,true);
				} // if
			} catch (err){
				raudrohi.tmg('96a3f15f-7650-42e2-8522-10f25081abd7',err);
			} // catch
		} // set_password_fields_table_visibility

		var b_password_rejection_message_display_needs_to_be_updated_=true;
		function update_password_rejection_message_display_properties(){
			try{
				if(b_password_string_available_but_unacceptable_===false){
					return;
				} // if
				if(b_password_rejection_message_display_needs_to_be_updated_===false){
					return;
				} // if
				var s_1=raudrohi.lang.word_wrap(
					s_password_rejection_message_,
					Math.floor(i_password_field_width_*1.5),"<br/>\n",
					' ',true);
				var s_rjmsg='<div style="color:'+
				s_password_rejection_message_color_+';">'+s_1+'</div>';
				widget_html_t2_disqualification_message_.set_content(
					s_rjmsg);
				b_password_rejection_message_display_needs_to_be_updated_=false;
			} catch (err){
				raudrohi.tmg('9625aa14-938f-49c6-a222-10f25081abd7',err);
			} // catch
		} // update_password_rejection_message_display_properties

		function set_subwidgets_visibility_according_to_states(){
			try{
				update_password_rejection_message_display_properties();
				var b_is_readonly=prc_.is_readonly_;
				switch(s_mode_){
					case 'add_new':
						prc_.mark_elemwidget_to_be_hidden(
							widget_partialmenu_t1_retain_or_modify_,true);
						if(b_is_readonly===false){
							set_password_fields_table_visibility(true);
						} else {
							set_password_fields_table_visibility(false);
						} // else
						break;
					case 'overwrite':
						prc_.mark_elemwidget_to_be_unhidden(
							widget_partialmenu_t1_retain_or_modify_);
						if(b_is_readonly===false){
							var s_label1=widget_partialmenu_t1_retain_or_modify_.get_content_s_label1();
							if(s_label1==='retain'){
								set_password_fields_table_visibility(false);
							} else {
								if(s_label1==='modify'){
									set_password_fields_table_visibility(true);
								} else {
									if(raudrohi.settings.debug_JavaScript){
										throw raudrohi.tmg(
											'cd2b2241-9802-4da9-b222-10f25081abd7',
											'There\'s no branching for s_label1(=='+
											s_label1+').');
									} // if
								} // else
							} // else
						} else { // b_is_readonly===true
							set_password_fields_table_visibility(false);
						} // else
						break;
					default:
						if(raudrohi.settings.debug_JavaScript){
							throw raudrohi.tmg(
								'28efda11-17c4-4986-b312-10f25081abd7',
								'There\'s no branching for s_mode_(=='+
								s_mode_+').');
						} // if
				} // switch
			} catch (err){
				raudrohi.tmg('491b05f3-80e2-4ae6-9512-10f25081abd7',err);
			} // catch
		} // set_subwidgets_visibility_according_to_states
		//-----------------------------------------------------------------
		prc_.customizable.compulsory.render_editable=function(){
			try{
				create_containers();
				set_subwidgets_visibility_according_to_states();
			} catch (err){
				raudrohi.tmg('ada7e433-a315-4c85-8312-10f25081abd7',err);
			} // catch
		} // prc_.customizable.compulsory.render_editable


		prc_.customizable.compulsory.render_readonly=function(){
			try{
				create_containers();
				set_subwidgets_visibility_according_to_states();
			} catch (err){
				raudrohi.tmg('a75ec8f4-29e5-40ee-a312-10f25081abd7',err);
			} // catch
		} // prc_.customizable.compulsory.render_readonly

		//-----------------------------------------------------------------
		self_public_.private_code_.evh_.evh_partialmenu_t1_retain_or_modify_selected=function(mi){
			try{
				set_subwidgets_visibility_according_to_states();
			} catch (err){
				raudrohi.tmg('46556243-33d9-473a-ae12-10f25081abd7',err);
			} // catch
		} // self_public_.private_code_.evh_.evh_partialmenu_t1_retain_or_modify_selected
		//-----------------------------------------------------------------
		// Format described next to the
		// this.register_acceptance_verification_function
		var ar_acceptance_verification_functions_=new Array();

		// The func_in is expected to return an array, where 
		// ar[0]==<boolean true for failure, otherwise false>
		// ar[1]==<empty string if no failure, otherwise password rejection message>
		this.register_acceptance_verification_function=function(func_in){
			try{
				var i=0;
				var x=null;
				if(raudrohi.settings.debug_JavaScript===true){			
					raudrohi.base.assert_isFunction(func_in,'func_in',
						'18e8d831-b304-41af-a212-10f25081abd7');
					var s_err_msg='The registered password acceptance '+
					'verification function does not meet the specification.';
					var ar_x=func_in('abra','cadabra');
					raudrohi.base.assert_isArray(ar_x,'ar_x==func_in(...)',
						'9f47a82f-22c0-4eee-8312-10f25081abd7',s_err_msg);
					i=ar_x.length;
					if(i!=2){
						raudrohi.tmg('9184d1a1-48fa-4dcf-b812-10f25081abd7',
							s_err_msg+
							' 2 != (func_in(...)==ar_x).length == '+i);
					} // if
					x=ar_x[0];
					raudrohi.base.assert_isBoolean(x,'ar_x[0]',
						'01baf223-a8f8-4e75-a312-10f25081abd7',s_err_msg);
					x=ar_x[1];
					raudrohi.base.assert_isString(x,'ar_x[1]',
						'59f38bd7-652e-4e8e-8102-10f25081abd7',s_err_msg);
				} // if
				ar_acceptance_verification_functions_.push(func_in);
				if(b_acceptable_password_string_available_===true){
					// The new function might deem the
					// previously accepted password unacceptable.
					password_acceptance_verification();
				} // if
			} catch (err){
				raudrohi.tmg('38611112-1724-4418-9402-10f25081abd7',err);
			} // catch
		} // register_acceptance_verification_function

		function remove_all_acceptance_verification_functions_except_mismatch(){
			try{
				ar_acceptance_verification_functions_=new Array();
				if(b_password_string_available_but_unacceptable_===true){
					// The password might have been deemed
					// unacceptable by one of the functions
					// that got unregistered here.
					password_acceptance_verification();
				} // if
			} catch (err){
				raudrohi.tmg('59185835-f651-4f78-b202-10f25081abd7',err);
			} // catch
		} // remove_all_acceptance_verification_functions_except_mismatch

		function password_acceptance_verification_rejected_by_func(s_line_1,s_line_2){
			try{
				var b_password_rejected=false;
				var i_len=ar_acceptance_verification_functions_.length;
				var i=0;
				var func_verification;
				var ar=null;
				var s_1=null;
				for(i=0;i<i_len;i++){
					func_verification=ar_acceptance_verification_functions_[i];
					ar=func_verification(s_line_1,s_line_2);
					if(ar[0]===true){
						s_1=ar[1];
						if(s_password_rejection_message_!==s_1){
							s_password_rejection_message_=s_1;
							b_password_rejection_message_display_needs_to_be_updated_=true;
						} // if
						b_password_rejected=true;
						b_acceptable_password_string_available_=false;
						break;
					} // if
				} // for
				return b_password_rejected;
			} catch (err){
				raudrohi.tmg('77861a3e-1581-4b68-9202-10f25081abd7',err);
			} // catch
		} // password_acceptance_verification_rejected_by_func

		function password_acceptance_verification(){
			try{
				b_acceptable_password_string_available_=false;
				b_password_string_available_but_unacceptable_=false;
				var rgx=RegExp("[\\n]+$","g");
				var s_lc_emptystring="";
				var s_line_1=widget_textarea_t1_line_1_.get_content().replace(
					rgx,s_lc_emptystring);
				var s_line_2=widget_textarea_t1_line_2_.get_content().replace(
					rgx,s_lc_emptystring);
				if(s_line_1.length!==s_line_2.length){
					if(s_password_rejection_message_!==s_password_mismatch_message_){
						s_password_rejection_message_=s_password_mismatch_message_;
						b_password_rejection_message_display_needs_to_be_updated_=true;
					} // if
					b_password_string_available_but_unacceptable_=true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if
				if(s_line_1.length===0){ // ===s_line_2.lenght
					s_password_rejection_message_="Password length==0."; // hidden anyway
					b_password_rejection_message_display_needs_to_be_updated_=true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if
				if(s_line_1!==s_line_2){
					s_password_rejection_message_=s_password_mismatch_message_;
					b_password_rejection_message_display_needs_to_be_updated_=true;
					b_password_string_available_but_unacceptable_=true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if

				if(password_acceptance_verification_rejected_by_func(s_line_1,s_line_2)===true){
					b_password_string_available_but_unacceptable_=true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if
				s_acceptable_password_string_=s_line_1;
				b_acceptable_password_string_available_=true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('8fc7d427-90e5-437d-9302-10f25081abd7',err);
			} // catch
		} // password_acceptance_verification


		//-----------------------------------------------------------------

		//wg_hooks_.evh_widget_textarea_t1_line_1_key_13=function(e) {
		// This function is meant to be overridden.
		//} // wg_hooks_.evh_widget_textarea_t1_line_2_key_13

		prc_.evh_.evh_widget_textarea_t1_line_1_key_blur_local=function(e){
			try{
				var s_line_2=widget_textarea_t1_line_2_.get_content();
				if(0<s_line_2.length){
					password_acceptance_verification();
				} // if
			} catch (err){
				raudrohi.tmg('7470ce34-413e-43d9-a102-10f25081abd7',err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_1_key_blur_local

		prc_.evh_.evh_widget_textarea_t1_line_1_key_13_local=function(e){
			try{
				var s_line_2=widget_textarea_t1_line_2_.get_content();
				if(0<s_line_2.length){
					password_acceptance_verification();
				} // if
				widget_textarea_t1_line_2_.set_focus();
			//wg_hooks_.evh_widget_textarea_t1_line_1_key_13(e);
			} catch (err){
				raudrohi.tmg('2d3e9194-09b4-4266-8702-10f25081abd7',err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_1_key_13_local

		wg_hooks_.evh_widget_textarea_t1_line_2_key_13=function(e) {
		// This function is meant to be overridden.
		} // wg_hooks_.evh_widget_textarea_t1_line_2_key_13

		prc_.evh_.evh_widget_textarea_t1_line_2_key_blur_local=function(e){
			try{
				password_acceptance_verification();
			} catch (err){
				raudrohi.tmg('19d34d2d-6c22-4e6b-b502-10f25081abd7',err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_2_key_blur_local

		prc_.evh_.evh_widget_textarea_t1_line_2_key_13_local=function(e){
			try{
				password_acceptance_verification();
				wg_hooks_.evh_widget_textarea_t1_line_2_key_13(e);
			} catch (err){
				raudrohi.tmg('fd82ab1e-1555-49e8-8302-10f25081abd7',err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_2_key_13_local


		//-----------------------------------------------------------------
		function initiate_widgets(){
			try{
				self_public_.set_line_1_legend('');
				self_public_.set_line_2_legend('');
				widget_partialmenu_t1_retain_or_modify_.private_code_.customizable.optional.evh_selection_impl=self_public_.private_code_.evh_.evh_partialmenu_t1_retain_or_modify_selected;
				// raudrohi_virtual_key_blur
				widget_textarea_t1_line_1_.set_keylistener('13',
					prc_.evh_.evh_widget_textarea_t1_line_1_key_13_local);
				widget_textarea_t1_line_2_.set_keylistener('13',
					prc_.evh_.evh_widget_textarea_t1_line_2_key_13_local);
				widget_textarea_t1_line_1_.set_keylistener(
					'raudrohi_virtual_key_blur',
					prc_.evh_.evh_widget_textarea_t1_line_1_key_blur_local);
				widget_textarea_t1_line_2_.set_keylistener(
					'raudrohi_virtual_key_blur',
					prc_.evh_.evh_widget_textarea_t1_line_2_key_blur_local);
			//self_public_.private_code_.evh_.evh_button_add_new_report=function(e){
			} catch (err){
				raudrohi.tmg('5a932851-2ab2-47d1-af02-10f25081abd7',err);
			} // catch
		} // initiate_widgets

		prc_.customizable.optional.create_subwidgets=function(){
			try{
				create_widgets_autogen();
				initiate_widgets();
			} catch (err){
				raudrohi.tmg('7f23ff49-2736-42fb-b2f1-10f25081abd7',err);
			} // catch
		} // prc_.customizable.optional.create_subwidgets=function(){

		//-----------------------------------------------------------------
		var s_mode_='add_new';
		this.set_mode=function(s_mode){
			try{
				var i=null;
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isString(
						s_mode,'s_mode','5e9a0533-fe8e-452b-93f1-10f25081abd7');
					i=s_mode.length;
					raudrohi.base.assert_isGreaterThanOrEqualTo(1,
						'1', '4685415d-f3d0-4d85-a5f1-10f25081abd7',
						i, 's_mode.length',' Empty strings are not allowed.');
					switch(s_mode){
						case 'add_new':
							break;           
						case 'overwrite':
							break;           
						default:
							if(raudrohi.settings.debug_JavaScript){
								throw raudrohi.tmg(
									'284a58f2-8012-4409-bcf1-10f25081abd7',
									'There\'s no branching for s_mode(=='+
									s_mode+').');
							} // if
					} // switch
				} // if
				if(s_mode_===s_mode){
					return;
				} // if
				s_mode_=""+s_mode;
				widget_partialmenu_t1_retain_or_modify_.set_content_by_s_label1(
					'modify');
				prc_.containers_html_cached_=false;
				prc_.repaint_if_graphical_and_not_hidden();
				// The duplication of widget_partialmenu_t1_retain_or_modify_
				// selection assignment is just to increase fault tolerance,
				// because the menu position really has to be "modify",
				// if the s_mode==="add_new" and one can not be too sure,
				// what will happen at the graphical side before
				// this function exits. In theory, if the JavaScript
				// is really a single-threaded application, the
				// secondary menu content assignment is not necessary,
				// but this is the WEB, which tends to be
				// somewhat crappy, so I'll better be safe than sorry.
				widget_partialmenu_t1_retain_or_modify_.set_content_by_s_label1(
					'modify');
			} catch (err){
				raudrohi.tmg('1aae9c40-9d7d-4dc3-a2f1-10f25081abd7',err);
			} // catch
		} // set_mode

		this.s_get_mode=function(){
			try{
				var s_out=""+s_mode_;
				return s_out;
			} catch (err){
				raudrohi.tmg('4c5b1d49-3af0-468a-b4f1-10f25081abd7',err);
			} // catch
		} // s_get_mode

		//-----------------------------------------------------------------
		var s_menu_position_='north';

		// s_menu_position inSet {"north", "south", "east", "west"}
		// The position is relative to the textfields. For example,
		// If the menu is to the right of the visible textfields, then
		// the  s_menu_position=="west".
		this.set_menu_position=function(s_menu_position){
			try{
				var i=null;
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isString(
						s_menu_position,'s_menu_position',
						'670a8150-92b7-407d-85f1-10f25081abd7');
					i=s_menu_position.length;
					raudrohi.base.assert_isGreaterThanOrEqualTo(1,
						'1', '85518194-6a13-4129-b5f1-10f25081abd7',
						i, 's_menu_position.length',
						' Empty strings are not allowed.');
				} // if
				if(s_menu_position_===s_menu_position){
					return;
				} // if
				switch(s_menu_position){
					case 'north':
						break;
					case 'south':
						break;
					case 'east':
						break;
					case 'west':
						break;
					default:
						if(raudrohi.settings.debug_JavaScript){
							throw raudrohi.tmg(
								'e064b52a-fba0-4a75-84f1-10f25081abd7',
								'There\'s no branching for s_menu_position(=='+
								s_menu_position+').');
						} // if
				} // switch
				s_menu_position_=""+s_menu_position;
				prc_.containers_html_cached_=false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('9fb52d3d-6a18-470d-91e1-10f25081abd7',err);
			} // catch
		} // set_menu_position

		this.s_get_menu_position=function(){
			try{
				var s_out=""+s_menu_position_;
				return s_out;
			} catch (err){
				raudrohi.tmg('a030843c-afaa-428a-83e1-10f25081abd7',err);
			} // catch
		} // s_get_menu_position

		//-----------------------------------------------------------------
		var i_password_field_width_=20;
		this.set_i_password_field_width=function(i_password_field_width){
			try{
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isNumber(
						i_password_field_width,'i_password_field_width',
						'9bf85ea1-fa5c-4534-aee1-10f25081abd7');
					raudrohi.lang.assert_is_a_whole_number(
						i_password_field_width,'i_password_field_width',
						'c7118453-e984-4c19-b1e1-10f25081abd7');
					raudrohi.base.assert_isGreaterThanOrEqualTo(5,
						'5', '3f3e3335-18b3-48f0-b3e1-10f25081abd7',
						i_password_field_width, 'i_password_field_width','');
				} // if
				if(i_password_field_width_===i_password_field_width){
					return;
				} // if
				i_password_field_width_=""+i_password_field_width;
				b_password_rejection_message_display_needs_to_be_updated_=true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('a2fc9745-917e-4d90-83e1-10f25081abd7',err);
			} // catch
		} // set_i_password_field_width

		this.s_get_i_password_field_width=function(){
			try{
				var i_out=0+i_password_field_width_;
				return i_out;
			} catch (err){
				raudrohi.tmg('3351d1e3-2e12-4d87-85e1-10f25081abd7',err);
			} // catch
		} // s_get_i_password_field_width

		//-----------------------------------------------------------------
		var i_password_field_legend_width_=15;
		this.set_i_password_field_legend_width=function(i_password_field_legend_width){
			try{
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isNumber(
						i_password_field_legend_width,'i_password_field_legend_width',
						'13f11840-4ee8-45c6-82e1-10f25081abd7');
					raudrohi.lang.assert_is_a_whole_number(
						i_password_field_legend_width,'i_password_field_legend_width',
						'af064835-8c47-477e-85e1-10f25081abd7');
					raudrohi.base.assert_isGreaterThanOrEqualTo(5,
						'5', '6f195b48-51b0-408d-a4e1-10f25081abd7',
						i_password_field_legend_width, 'i_password_field_legend_width','');
				} // if
				if(i_password_field_legend_width_===i_password_field_legend_width){
					return;
				} // if
				i_password_field_legend_width_=""+i_password_field_legend_width;
				prc_.containers_html_cached_=false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('2166d061-d0b0-467d-b8d1-10f25081abd7',err);
			} // catch
		} // set_i_password_field_legend_width

		this.s_get_i_password_field_legend_width=function(){
			try{
				var i_out=0+i_password_field_legend_width_;
				return i_out;
			} catch (err){
				raudrohi.tmg('630e0735-f980-4eb2-94d1-10f25081abd7',err);
			} // catch
		} // s_get_i_password_field_legend_width

		//-----------------------------------------------------------------
		var s_line_1_legend_='not_set';
		this.set_line_1_legend=function(s_line_1_legend){
			try{
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isString(
						s_line_1_legend,'s_line_1_legend',
						'a6ac494a-b31a-4823-b5d1-10f25081abd7');
				} // if
				if(s_line_1_legend_===s_line_1_legend){
					return;
				} // if
				s_line_1_legend_=""+s_line_1_legend;
				var s_wdwpd=raudrohi.lang.word_wrap(s_line_1_legend_,
					i_password_field_legend_width_,"<br/>\n",' ');
				widget_html_t2_line_1_legend_.set_content(s_wdwpd);
				prc_.containers_html_cached_=false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('87b10cca-5d0f-4269-93d1-10f25081abd7',err);
			} // catch
		} // set_line_1_legend

		this.s_get_line_1_legend=function(){
			try{
				var s_out=""+s_line_1_legend_;
				return s_out;
			} catch (err){
				raudrohi.tmg('e957052b-0335-424b-b3d1-10f25081abd7',err);
			} // catch
		} // s_get_line_1_legend

		//-----------------------------------------------------------------
		var s_line_2_legend_='not_set';
		this.set_line_2_legend=function(s_line_2_legend){
			try{
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isString(
						s_line_2_legend,'s_line_2_legend',
						'b2906d15-1ef6-4eea-91d1-10f25081abd7');
				} // if
				if(s_line_2_legend_===s_line_2_legend){
					return;
				} // if
				s_line_2_legend_=""+s_line_2_legend;
				var s_wdwpd=raudrohi.lang.word_wrap(s_line_2_legend_,
					i_password_field_legend_width_,"<br/>\n",' ');
				widget_html_t2_line_2_legend_.set_content(s_wdwpd);
				prc_.containers_html_cached_=false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('c68c5a2a-28ae-46b2-b4d1-10f25081abd7',err);
			} // catch
		} // set_line_2_legend

		this.s_get_line_2_legend=function(){
			try{
				var s_out=""+s_line_2_legend_;
				return s_out;
			} catch (err){
				raudrohi.tmg('d32d7435-8c3d-4ec4-91d1-10f25081abd7',err);
			} // catch
		} // s_get_line_2_legend

		//-----------------------------------------------------------------
		var s_password_mismatch_message_="The passowords don't match.";
		this.set_password_mismatch_message=function(s_password_mismatch_message){
			try{
				var i=null;
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isString(
						s_password_mismatch_message,'s_password_mismatch_message',
						'de6c8547-5c9b-43c7-94c1-10f25081abd7');
					i=s_password_mismatch_message.length;
					raudrohi.base.assert_isGreaterThanOrEqualTo(1,
						'1', '97f0421b-9c4d-485d-b4c1-10f25081abd7',
						i, 's_password_mismatch_message.length',
						' Empty strings are not allowed.');
				} // if
				if(s_password_mismatch_message_===s_password_mismatch_message){
					return;
				} // if
				s_password_mismatch_message_=""+s_password_mismatch_message;
				b_password_rejection_message_display_needs_to_be_updated_=true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('806d522c-917e-4e7a-84c1-10f25081abd7',err);
			} // catch
		} // set_password_mismatch_message

		this.s_get_password_mismatch_message=function(){
			try{
				var s_out=""+s_password_mismatch_message_;
				return s_out;
			} catch (err){
				raudrohi.tmg('477f7a22-fd0f-4484-82c1-10f25081abd7',err);
			} // catch
		} // s_get_password_mismatch_message

		//-----------------------------------------------------------------
		var s_password_rejection_message_color_=window.raudrohi.widgets.g1.theme.s_color_no;
		this.set_password_rejection_message_color=function(
			s_password_rejection_message_color){
			try{
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isString(
						s_password_rejection_message_color,
						's_password_rejection_message_color',
						'c4a17542-3826-4980-81c1-10f25081abd7');
					raudrohi.lang.assert_is_an_HTML_color(
						s_password_rejection_message_color,
						's_password_rejection_message_color',
						'208537b3-c762-4074-92c1-10f25081abd7');
				} // if
				if(s_password_rejection_message_color_===s_password_rejection_message_color){
					return;
				} // if
				s_password_rejection_message_color_=""+s_password_rejection_message_color;
				b_password_rejection_message_display_needs_to_be_updated_=true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err){
				raudrohi.tmg('59dc5b31-3ba0-48c6-b2c1-10f25081abd7',err);
			} // catch
		} // set_password_rejection_message_color

		this.s_get_password_rejection_message_color=function(){
			try{
				var s_out=""+s_password_rejection_message_color_;
				return s_out;
			} catch (err){
				raudrohi.tmg('64dd3e1f-0622-462d-b4c1-10f25081abd7',err);
			} // catch
		} // s_get_password_rejection_message_color

		//-----------------------------------------------------------------
		// Retunrs an instance namespace x with a format of:
		//
		// x.b_password_not_available
		// x.s_password
		// x.b_retain_old_password
		//
		// if(x.b_password_not_available===true){ x.s_password==='';}
		// if(x.b_retain_old_password===true){ x.b_password_not_available===true;}
		this.get_content=function(){
			try{
				var x_out={};
				x_out.s_password='';
				x_out.b_password_not_available=true;
				var s_label1=widget_partialmenu_t1_retain_or_modify_.get_content_s_label1();
				if(s_label1==='retain'){
					x_out.b_retain_old_password=true;
					return x_out;
				} // if
				x_out.b_retain_old_password=false; // s_label1==='modify'
				password_acceptance_verification();
				if(b_acceptable_password_string_available_===true){
					x_out.s_password=''+s_acceptable_password_string_;
					x_out.b_password_not_available=false;
				} // if
				return x_out;
			} catch (err){
				raudrohi.tmg('58fbd631-7084-45ad-85b1-10f25081abd7',err);
			} // catch
		} // get_content

		//-----------------------------------------------------------------
		this.get_content_2_collection_t1=function(ht){
			try{
				if(raudrohi.settings.debug_JavaScript===true){
					raudrohi.base.assert_isObject(ht,'ht',
						'b979d854-3a2c-4e0e-b5b1-10f25081abd7');
				} // if
				var s_sb_set=raudrohi.wg_processing_t1.s_key_field_set(
					self_public_);
				var s_dbf_key=raudrohi.wg_processing_t1.s_key_field(
					self_public_);
				var x=self_public_.get_content();
				if(x.b_retain_old_password===true){
					ht.put(s_dbf_key,' ');
					ht.put(s_sb_set,'f');
					return;
				} // if
				if(x.b_password_not_available===true){
					raudrohi.tmg('73078c47-6448-4a58-84b1-10f25081abd7',
						'self_public_.get_content().b_retain_old_password===false and '+
						'self_public_.get_content().b_password_not_available===true , but'+
						'the self_public_.get_content_2_collection_t1(...) got called. '+
						'The parent widget is expected to verify that the '+
						'self_public_.get_content().b_password_not_available===false '+
						'before calling the self_public_.get_content_2_collection_t1(...)'+
						'');
				} // if
				ht.put(s_dbf_key,x.s_password);
				ht.put(s_sb_set,'t');
			} catch (err){
				raudrohi.tmg('dceb951f-0f34-4a21-81b1-10f25081abd7',err);
			} // catch
		} // get_content_2_collection_t1

		this.set_content_from_collection_t1=function(ht){
			try{
				// Passwords are never expected to be sent from the
				// server.
				self_public_.set_mode('overwrite');
				widget_partialmenu_t1_retain_or_modify_.set_content_by_s_label1(
					'retain');
			} catch (err){
				raudrohi.tmg('8bad0c2b-9d88-404f-85b1-10f25081abd7',err);
			} // catch
		} // set_content_from_collection_t1

		//-----------------------------------------------------------------
		prc_.customizable.optional.startup_hook = function() {
			try{
			// This function can be deleted from here, because
			// it is already defined in the pile of methods.
			} catch (err){
				raudrohi.tmg('10ae0803-45df-46e7-8fb1-10f25081abd7',err);
			} // catch
		} // prc_.customizable.optional.startup_hook

		prc_.customizable.optional.shutdown_hook = function() {
			try{
			// This function can be deleted from here, because
			// it is already defined in the pile of methods.
			} catch (err){
				raudrohi.tmg('54c01b91-df52-47bb-95b1-10f25081abd7',err);
			} // catch
		} // prc_.customizable.optional.shutdown_hook

		self_public_.startup_sequence_init();
	} catch (err){
		raudrohi.tmg('204c9017-4266-4c78-a3b1-10f25081abd7',err);
	} // catch
} // raudrohi.widgets.g1.password_editor_t1

//-------------------------------------------------------------------------
