<?php
//=========================================================================
// Copyright (c) 2011, martin.vahi@softf1.com that has an
// Estonian personal identification code of 38108050020.
// This file is in public domain.
//=========================================================================

class raudrohi_configuration {
	public static $s_ip_address='192.168.0.102';

// The web server does not have the same
// environment variable values available to it
// as the user has. One of the ways, how to
// be able to execute development related
// scripts from PHP code, i.e. to start them
// by the web server, is to feed the environment
// variables to the bash scripts.

// RENESSAATOR_BLOCK_START
// RENESSAATOR_BLOCK_ID=block_1
// RENESSAATOR_SOURCE_LANGUAGE=Ruby
// RENESSAATOR_SOURCE_START
// ar_envnames=["SIREL_HOME","KIBUVITS_HOME","RUBY_HOME","GEM_HOME"]
// s_fields=""
// s_envexport=""
// ar_envnames.each do |s_envname|
// s_envvalue=ENV[s_envname]
// s_fields=s_fields+
// "public static $s_fp_"+s_envname.downcase+"='"+s_envvalue+"';\n"
// s_envexport=s_envexport+
// "export "+s_envname+"=\""+s_envvalue+"\"; "
// end # loop
// puts s_fields
// puts "\n public static $s_envexport='"+s_envexport+"';"
// puts "\n public static $s_devel_username='"+`whoami`.gsub(/[\n]/,"")+"';"
// RENESSAATOR_SOURCE_END
//
// RENESSAATOR_AUTOGENERATED_TEXT_START
	public static $s_fp_sirel_home='/home/zornilemma/Projektid/progremise_infrastruktuur/teeke/sirel/sirel_liivakast/sirel';
	public static $s_fp_kibuvits_home='/home/zornilemma/Projektid/progremise_infrastruktuur/teeke/kibuvits/kibuvits_liivakast/kibuvits/src';
	public static $s_fp_ruby_home='/home/zornilemma/m_local/bin_p/Ruby/peamine_realisatsioon/1.9.2/v_1_9_2_p180';
	public static $s_fp_gem_home='/home/zornilemma/m_local/bin_p/Ruby/peamine_realisatsioon/1.9.2/v_1_9_2_p180/mv_GEMs';

	public static $s_envexport='export SIREL_HOME="/home/zornilemma/Projektid/progremise_infrastruktuur/teeke/sirel/sirel_liivakast/sirel"; export KIBUVITS_HOME="/home/zornilemma/Projektid/progremise_infrastruktuur/teeke/kibuvits/kibuvits_liivakast/kibuvits/src"; export RUBY_HOME="/home/zornilemma/m_local/bin_p/Ruby/peamine_realisatsioon/1.9.2/v_1_9_2_p180"; export GEM_HOME="/home/zornilemma/m_local/bin_p/Ruby/peamine_realisatsioon/1.9.2/v_1_9_2_p180/mv_GEMs"; ';

	public static $s_devel_username='zornilemma';

// RENESSAATOR_AUTOGENERATED_TEXT_END
// RENESSAATOR_BLOCK_END


} // class raudrohi_configuration

define('s_path_lib_sirel',$s_fp_sirel_home);

//=========================================================================
?>

