//=========================================================================

raudrohi.widgets.g1.canvas_2d_t1 = function (s_html_id, i_width, i_height) {
    try {
        if (raudrohi_settings_debug_JavaScript === true) {
            raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(1, '1',
                '22b9fe50-fc75-44b7-b596-a0a350705dd7', i_width, 'i_width');
            raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(1, '1',
                '5678bb5b-91b9-4794-8596-a0a350705dd7', i_height, 'i_height');
        } // if
        var i_width_ = i_width;
        var i_height_ = i_height;

        // RENESSAATOR_BLOCK_START
// RENESSAATOR_BLOCK_ID=block_1
// RENESSAATOR_SOURCE_LANGUAGE=Ruby
// RENESSAATOR_SOURCE_START
// RAUDROHI_HOME=ENV['RAUDROHI_HOME']
// require(RAUDROHI_HOME+"/src/dev_tools/code_generation/raudrohi_cg0.rb")
// require(RAUDROHI_CODE_GENERATION+"/by_file/raudrohi_js_widgets_canvas_2d_t1_block_1.rb")
// RENESSAATOR_SOURCE_END
// 
// RENESSAATOR_AUTOGENERATED_TEXT_START
// RENESSAATOR_STDERR_START
// /home/ts2/Projektid/progremise_infrastruktuur/teeke/raudrohi/juur_liivakast/raudrohi/src/dev_tools/lib/mmmv_devel_tools/src/bonnet/lib/kibuvits_ruby_library/src/include/kibuvits_boot.rb:270: warning: Insecure world writable dir /tmp/ in PATH, mode 041777
// RENESSAATOR_STDERR_END
    if(raudrohi_settings_debug_JavaScript===true){
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_debug_verification 
            raudrohi.base.assert_is_HTML_ID(s_html_id,'s_html_id',
                '33d34243-4c64-4981-ac10-12d060705dd7');

    } // if

    if(raudrohi_settings_debug_JavaScript===true){
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_debug_verification 
            raudrohi.base.assert_isString(s_html_id,'s_html_id',
                'e1d38b4f-f874-42d3-9420-12d060705dd7');

    } // if
     //---widget--boilerplate_1_--start--
        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_widget 
		var self_public_=this;
		var pileofmethods_t1_=new raudrohi.widgets.g1.pileofmethods_t1(
                 self_public_,'raudrohi.widgets.g1.canvas_2d_t1',
                 s_html_id);
		var prc_=self_public_.private_code_;
		var wg_hooks_=self_public_.wg_hooks_;
     //---widget--boilerplate_1_--end----





   		function create_widgets_autogen( ){
				        // WARNING: This function resides in an autogeneration region.
        // This code has been autogenerated by: Raudrohi_cg_widget 
			try{
				 			} catch(err){
				raudrohi.tmg('4d45f4d4-8712-41a4-9721-12d060705dd7',err);
			} // catch
		} // create_widgets_autogen


// RENESSAATOR_AUTOGENERATED_TEXT_END
// RENESSAATOR_BLOCK_END

        //-----------------------------------------------------------------
        this.set_size = function (i_width, i_heigh) {
            try {
                if (raudrohi_settings_debug_JavaScript === true) {
                    raudrohi.base.assert_is_HTML_ID(s_html_id, 's_html_id',
                        '55424712-cb3e-47cc-b896-a0a350705dd7');
                    raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(1, '1',
                        '22b9fe50-fc75-44b7-b596-a0a350705dd7', i_width, 'i_width');
                    raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(1, '1',
                        '5678bb5b-91b9-4794-8596-a0a350705dd7', i_height, 'i_height');
                } // if
                i_width_ = i_width;
                i_height_ = i_height;
                prc_.containers_html_cached_=false;
            } catch (err) {
                raudrohi.tmg('11481a47-98fc-4467-8696-a0a350705dd7', err);
            } // catch
        } // set_size


        //-----------------------------------------------------------------

        var b_create_containers_s_password_fields_table_cached_ = false;

        function create_containers() {
            try {
                if (prc_.containers_html_cached_ !== true) {
                    var s_lines = null;
                    prc_.containers_html_cache_ = raudrohi.lang.cg_table_t1(
                        s_lines, ar_class_names);
                    prc_.containers_html_cached_ = true;
                } // if
                var s_container = prc_.containers_html_cache_;
                raudrohi.base.set_innerHTML(prc_.container_id_, s_container);
            } catch (err) {
                raudrohi.tmg('31bdf43d-3fb6-4cfb-9496-a0a350705dd7', err);
            } // catch
        } // create_containers

        //-----------------------------------------------------------------

        //prc_.content_set_=false;

        //-----------------------------------------------------------------

        prc_.customizable.compulsory.render_editable = function () {
            try {
                create_containers();
                set_subwidgets_visibility_according_to_states();
            } catch (err) {
                raudrohi.tmg('526ebb13-f7fb-43ec-8296-a0a350705dd7', err);
            } // catch
        } // prc_.customizable.compulsory.render_editable

        prc_.customizable.compulsory.render_readonly =
        prc_.customizable.compulsory.render_editable;

        //-----------------------------------------------------------------

        /*
         self_public_.private_code_.evh_.evh_mouse_moved= function (mi) {
         try {
         set_subwidgets_visibility_according_to_states();
         } catch (err) {
         raudrohi.tmg('86f2d337-ab41-40c7-b296-a0a350705dd7', err);
         } // catch
         } // self_public_.private_code_.evh_.evh_mouse_moved
         */

        //-----------------------------------------------------------------

        this.ht_get_content_spec_2 = function () {
            try {
                var ht_out = new Hashtable();
                return ht_out;
            } catch (err) {
                raudrohi.tmg('76b63003-7b2b-4753-8d86-a0a350705dd7', err);
            } // catch
        } // ht_get_content_spec_2

        //-----------------------------------------------------------------
        this.get_content_2_collection_t2 = function (ht) {
            try {
                if (raudrohi_settings_debug_JavaScript === true) {
                    raudrohi.base.assert_isObject(ht, 'ht',
                        '5fac984b-8858-49d4-b186-a0a350705dd7');
                } // if
                var ht_content = self_public_.ht_get_content_spec_2();
                var s_progfte = raudrohi.lang.ht2ProgFTE(ht_content);

                var s_sb_set = raudrohi.wg_processing_t1.s_key_field_set(
                    self_public_);
                var s_dbf_key = raudrohi.wg_processing_t1.s_key_field(
                    self_public_);
                var x = self_public_.get_content();
                if (x.b_retain_old_password === true) {
                    ht.put(s_dbf_key, ' ');
                    ht.put(s_sb_set, 'f');
                    return;
                } // if
                if (x.b_password_not_available === true) {
                    raudrohi.tmg('05ba6e21-8981-4663-9486-a0a350705dd7',
                        'self_public_.get_content().b_retain_old_password===false and ' +
                        'self_public_.get_content().b_password_not_available===true , but' +
                        'the self_public_.get_content_2_collection_t1(...) got called. ' +
                        'The parent widget is expected to verify that the ' +
                        'self_public_.get_content().b_password_not_available===false ' +
                        'before calling the self_public_.get_content_2_collection_t1(...)' +
                        '');
                } // if
                ht.put(s_dbf_key, x.s_password);
                ht.put(s_sb_set, 't');
            } catch (err) {
                raudrohi.tmg('7937a04d-1aab-4af1-8486-a0a350705dd7', err);
            } // catch
        } // get_content_2_collection_t1

        this.set_content_from_collection_t1 = function (ht) {
            try {
                // Passwords are never expected to be sent from the
                // server.
                self_public_.set_mode('overwrite');
                widget_partialmenu_t1_retain_or_modify_.set_content_by_s_label1(
                    'retain');
            } catch (err) {
                raudrohi.tmg('045fbe5a-d398-46d2-8186-a0a350705dd7', err);
            } // catch
        } // set_content_from_collection_t1

        //-----------------------------------------------------------------

        self_public_.startup_sequence_init();
    }
    catch
        (err) {
        raudrohi.tmg('1bc26a42-b25c-430b-af86-a0a350705dd7', err);
    } // catch
} // raudrohi.widgets.g1.canvas_2d_t1

//-------------------------------------------------------------------------
