//=========================================================================

// It's instantiated in the library constructor.
raudrohi.widgets.g1.password_editor_t1 = function(s_html_id, parent_instance) {
	try {

		// RENESSAATOR_BLOCK_START
		// RENESSAATOR_BLOCK_ID=block_1
		// RENESSAATOR_SOURCE_LANGUAGE=Ruby
		// RENESSAATOR_SOURCE_START
		// RAUDROHI_HOME=ENV['RAUDROHI_HOME']
		// require(RAUDROHI_HOME+"/src/dev_tools/code_generation/raudrohi_cg0.rb")
		// require(RAUDROHI_CODE_GENERATION+"/by_file/raudrohi_js_widgets_password_editor_t1_block_1.rb")
		// RENESSAATOR_SOURCE_END
		//
		// RENESSAATOR_AUTOGENERATED_TEXT_START

		if (raudrohi_settings_debug_JavaScript === true) {
			// WARNING: This function resides in an autogeneration region.
			// This code has been autogenerated by: Raudrohi_cg_debug_verification
			raudrohi.base.assert_isString(s_html_id, 's_html_id',
				'47bffe71-02bb-453b-8c1f-a09010703dd7');
			raudrohi.base.assert_isObject(parent_instance, 'parent_instance',
				'1d696193-da73-4bc9-9e3f-a09010703dd7');

		} // if
		//---widget--boilerplate_1_--start--
		// WARNING: This function resides in an autogeneration region.
		// This code has been autogenerated by: Raudrohi_cg_widget
		var self_public_ = this;
		var pileofmethods_t1_ = new raudrohi.widgets.g1.pileofmethods_t1(
			self_public_, 'raudrohi.widgets.g1.password_editor_t1',
			s_html_id);
		var prc_ = self_public_.private_code_;
		var wg_hooks_ = self_public_.wg_hooks_;
		//---widget--boilerplate_1_--end----


		prc_.parent_instance_ = parent_instance;

		var widget_partialmenu_t1_retain_or_modify_ = null;
		var id_partialmenu_t1_retain_or_modify_ = prc_.html_id_ + '_partialmenu_t1_retain_or_modify';
		var widget_textarea_t1_line_1_ = null;
		var id_textarea_t1_line_1_ = prc_.html_id_ + '_textarea_t1_line_1';
		var widget_textarea_t1_line_2_ = null;
		var id_textarea_t1_line_2_ = prc_.html_id_ + '_textarea_t1_line_2';
		var widget_html_t2_line_1_legend_ = null;
		var id_html_t2_line_1_legend_ = prc_.html_id_ + '_html_t2_line_1_legend';
		var widget_html_t2_line_2_legend_ = null;
		var id_html_t2_line_2_legend_ = prc_.html_id_ + '_html_t2_line_2_legend';
		var widget_html_t2_disqualification_message_ = null;
		var id_html_t2_disqualification_message_ = prc_.html_id_ + '_html_t2_disqualification_message';



		function create_widgets_autogen( ) {
			// WARNING: This function resides in an autogeneration region.
			// This code has been autogenerated by: Raudrohi_cg_widget
			try {
				widget_partialmenu_t1_retain_or_modify_ = new
					raudrohi.widgets.g1.partialmenu_t1(
					id_partialmenu_t1_retain_or_modify_, self_public_,
					40, 40, 1,
					"There is a flaw.  '41589673-0339-4990-8e2f-a09010703dd7'",
					'partialmenu_t1_mode_1', 'partialmenu_t1_containertype_vertical_1');
				widget_partialmenu_t1_retain_or_modify_.s_field_name_in_parent = 'retain_or_modify';
				prc_.register_subwidget(
					widget_partialmenu_t1_retain_or_modify_, 'visible');

				var ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7 = [];
				var x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7;
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7 = {};
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label1 = 'retain';
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label2 = 'Retain';
				ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7.push(x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7);
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7 = {};
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label1 = 'modify';
				x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7.s_label2 = 'Modify';
				ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7.push(x_autogenerated_tmpvar_e782f738_37ea_4d78_a33b_12127151abd7);

				widget_partialmenu_t1_retain_or_modify_.set_menu_content(ar_autogenerated_tmpvar_f0514649_dd88_4fb0_b13b_12127151abd7)
				var ht_widget_textarea_t1_line_1_params = raudrohi.base.pool_of_hashtables.get_empty_hashtable();
				ht_widget_textarea_t1_line_1_params.put('type', 'password');
				widget_textarea_t1_line_1_ = new raudrohi.widgets.g1.textarea_t1(
					id_textarea_t1_line_1_, i_password_field_width_, 1,
					ht_widget_textarea_t1_line_1_params);
				widget_textarea_t1_line_1_.set_alignment('west');
				prc_.register_subwidget(widget_textarea_t1_line_1_, 'hidden');
				widget_textarea_t1_line_1_.s_field_name_in_parent = 'line_1';
				raudrohi.base.pool_of_hashtables.return_used_hashtable(ht_widget_textarea_t1_line_1_params);

				var ht_widget_textarea_t1_line_2_params = raudrohi.base.pool_of_hashtables.get_empty_hashtable();
				ht_widget_textarea_t1_line_2_params.put('type', 'password');
				widget_textarea_t1_line_2_ = new raudrohi.widgets.g1.textarea_t1(
					id_textarea_t1_line_2_, i_password_field_width_, 1,
					ht_widget_textarea_t1_line_2_params);
				widget_textarea_t1_line_2_.set_alignment('west');
				prc_.register_subwidget(widget_textarea_t1_line_2_, 'hidden');
				widget_textarea_t1_line_2_.s_field_name_in_parent = 'line_2';
				raudrohi.base.pool_of_hashtables.return_used_hashtable(ht_widget_textarea_t1_line_2_params);

				widget_html_t2_line_1_legend_ = new raudrohi.widgets.g1.html_t2(
					id_html_t2_line_1_legend_, self_public_);
				widget_html_t2_line_1_legend_.s_field_name_in_parent = 'line_1_legend';
				prc_.register_subwidget(
					widget_html_t2_line_1_legend_, 'hidden');

				widget_html_t2_line_2_legend_ = new raudrohi.widgets.g1.html_t2(
					id_html_t2_line_2_legend_, self_public_);
				widget_html_t2_line_2_legend_.s_field_name_in_parent = 'line_2_legend';
				prc_.register_subwidget(
					widget_html_t2_line_2_legend_, 'hidden');

				widget_html_t2_disqualification_message_ = new raudrohi.widgets.g1.html_t2(
					id_html_t2_disqualification_message_, self_public_);
				widget_html_t2_disqualification_message_.s_field_name_in_parent = 'disqualification_message';
				prc_.register_subwidget(
					widget_html_t2_disqualification_message_, 'hidden');

			} catch (err) {
				raudrohi.tmg('30a56954-83bb-40e4-9f1f-a09010703dd7', err);
			} // catch
		} // create_widgets_autogen


		// RENESSAATOR_AUTOGENERATED_TEXT_END
		// RENESSAATOR_BLOCK_END
		//-----------------------------------------------------------------
		var s_create_containers_s_password_fields_table_ = '';
		var b_create_containers_s_password_fields_table_cached_ = false;
		function create_containers_s_password_fields_table() {
			try {
				if (b_create_containers_s_password_fields_table_cached_ !== true) {
					var s_lines = '' +
						'<tr>' +
						"\n" +
						'<td class="" colspan="1">' +
						'<div id="' + id_html_t2_line_1_legend_ + '_div"></div></td>' +
						"\n" +
						'<td class="" colspan="1">' +
						'<div id="' + id_textarea_t1_line_1_ + '_div"></div></td>' +
						"\n" +
						'</tr>' +
						'<tr>' +
						"\n" +
						'<td class="" colspan="1"></td>' +
						"\n" +
						'<td class="" colspan="1">' +
						'<div id="' + id_html_t2_disqualification_message_ + '_div"></div></td>' +
						"\n" +
						'</tr>' +
						'<tr>' +
						"\n" +
						'<td class="" colspan="1">' +
						'<div id="' + id_html_t2_line_2_legend_ + '_div"></div></td>' +
						"\n" +
						'<td class="" colspan="1">' +
						'<div id="' + id_textarea_t1_line_2_ + '_div"></div></td>' +
						"\n" +
						'</tr>' +
						'';

					var ar_class_names = ["raudrohi_positioning_table"]; // raudrohi_visible_table
					s_create_containers_s_password_fields_table_ = raudrohi.lang.cg_table_t1("" +
						s_lines,
						ar_class_names);
					b_create_containers_s_password_fields_table_cached_ = true;
				} // if
				var s_out = s_create_containers_s_password_fields_table_;
				return s_out;
			} catch (err) {
				raudrohi.tmg('7b9c7db2-5e05-4546-9e1f-a09010703dd7', err);
			} // catch
		} // create_containers_s_password_fields_table

		//-----------------------------------------------------------------
		function create_containers_s_lines_north() {
			try {
				var s_out = '' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1">' +
					'<div id="' + id_partialmenu_t1_retain_or_modify_ + '_div"></div></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1">' +
					create_containers_s_password_fields_table() +
					'</td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'';
				return s_out;
			} catch (err) {
				raudrohi.tmg('363980f4-a94b-4eb2-9e3f-a09010703dd7', err);
			} // catch
		} // create_containers_s_lines_north

		function create_containers_s_lines_south() {
			try {
				var s_out = '' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1">' +
					create_containers_s_password_fields_table() +
					'</td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1">' +
					'<div id="' + id_partialmenu_t1_retain_or_modify_ + '_div"></div></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'';
				return s_out;
			} catch (err) {
				raudrohi.tmg('56275811-4606-4438-a13f-a09010703dd7', err);
			} // catch
		} // create_containers_s_lines_south

		function create_containers_s_lines_east() {
			try {
				var s_out = '' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1">' +
					create_containers_s_password_fields_table() +
					'</td>' +
					"\n" +
					'<td class="" colspan="1">' +
					'<div id="' + id_partialmenu_t1_retain_or_modify_ + '_div"></div></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'';
				return s_out;
			} catch (err) {
				raudrohi.tmg('c3362fc7-8e6e-4b0c-a85f-a09010703dd7', err);
			} // catch
		} // create_containers_s_lines_east

		function create_containers_s_lines_west() {
			try {
				var s_out = '' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1">' +
					'<div id="' + id_partialmenu_t1_retain_or_modify_ + '_div"></div></td>' +
					"\n" +
					'<td class="" colspan="1">' +
					create_containers_s_password_fields_table() +
					'</td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'<tr>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'<td class="" colspan="1"></td>' +
					"\n" +
					'</tr>' +
					'';
				return s_out;
			} catch (err) {
				raudrohi.tmg('14680315-2a77-40ff-994e-a09010703dd7', err);
			} // catch
		} // create_containers_s_lines_west

		function create_containers() {
			try {
				if (!prc_.containers_html_cached_) {
					var s_lines = null;
					switch (s_menu_position_) {
						case 'north':
							s_lines = create_containers_s_lines_north();
							break;
						case 'south':
							s_lines = create_containers_s_lines_south();
							break;
						case 'east':
							s_lines = create_containers_s_lines_east();
							break;
						case 'west':
							s_lines = create_containers_s_lines_west();
							break;
						default:
							if (raudrohi_settings_debug_JavaScript) {
								throw raudrohi.tmg(
									'954593da-c0e6-4fcd-aa3e-a09010703dd7',
									'There\'s no branching for s_menu_position(==' +
									s_menu_position_ + ').');
							} // if
					} // switch
					var ar_class_names = ["raudrohi_positioning_table"]; // raudrohi_visible_table
					prc_.containers_html_cache_ = raudrohi.lang.cg_table_t1(
						s_lines, ar_class_names);
					prc_.containers_html_cached_ = true;
				} // if
				var s_container = prc_.containers_html_cache_;
				raudrohi.base.set_innerHTML(prc_.container_id_, s_container);
			} catch (err) {
				raudrohi.tmg('919609ff-73ef-4c4e-843e-a09010703dd7', err);
			} // catch
		} // create_containers

		//-----------------------------------------------------------------
		//prc_.content_set_=false;
		var b_acceptable_password_string_available_ = false;
		var b_password_string_available_but_unacceptable_ = false;
		var s_acceptable_password_string_ = '';
		var s_password_rejection_message_ = '';

		function set_password_fields_table_visibility(b_true_if_visible) {
			try {
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isBoolean(
						b_true_if_visible, 'b_true_if_visible',
						'46de3ae3-cf06-4d24-8d4e-a09010703dd7');
				} // if                
				if (b_true_if_visible === true) {
					if (b_password_string_available_but_unacceptable_ === true) {
						prc_.mark_elemwidget_to_be_unhidden(
							widget_html_t2_disqualification_message_);
					} else {
						prc_.mark_elemwidget_to_be_hidden(
							widget_html_t2_disqualification_message_, true);
					} // else
					prc_.mark_elemwidget_to_be_unhidden(
						widget_html_t2_line_1_legend_);
					prc_.mark_elemwidget_to_be_unhidden(
						widget_html_t2_line_2_legend_);
					prc_.mark_elemwidget_to_be_unhidden(
						widget_textarea_t1_line_1_);
					prc_.mark_elemwidget_to_be_unhidden(
						widget_textarea_t1_line_2_);
				} else { // hide it all
					prc_.mark_elemwidget_to_be_hidden(
						widget_html_t2_disqualification_message_, true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_html_t2_line_1_legend_, true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_html_t2_line_2_legend_, true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_textarea_t1_line_1_, true);
					prc_.mark_elemwidget_to_be_hidden(
						widget_textarea_t1_line_2_, true);
				} // if
			} catch (err) {
				raudrohi.tmg('2f0c36b1-ed49-4895-b55e-a09010703dd7', err);
			} // catch
		} // set_password_fields_table_visibility

		var b_password_rejection_message_display_needs_to_be_updated_ = true;
		function update_password_rejection_message_display_properties() {
			try {
				if (b_password_string_available_but_unacceptable_ === false) {
					return;
				} // if
				if (b_password_rejection_message_display_needs_to_be_updated_ === false) {
					return;
				} // if
				var s_1 = raudrohi.lang.word_wrap(
					s_password_rejection_message_,
					Math.floor(i_password_field_width_ * 1.5), "<br/>\n",
					' ', true);
				var s_rjmsg = '<div style="color:' +
					s_password_rejection_message_color_ + ';">' + s_1 + '</div>';
				widget_html_t2_disqualification_message_.set_content(
					s_rjmsg);
				b_password_rejection_message_display_needs_to_be_updated_ = false;
			} catch (err) {
				raudrohi.tmg('a5a0afcf-106b-4cdd-be3e-a09010703dd7', err);
			} // catch
		} // update_password_rejection_message_display_properties

		function set_subwidgets_visibility_according_to_states() {
			try {
				update_password_rejection_message_display_properties();
				var b_is_readonly = prc_.is_readonly_;
				switch (s_mode_) {
					case 'add_new':
						prc_.mark_elemwidget_to_be_hidden(
							widget_partialmenu_t1_retain_or_modify_, true);
						if (b_is_readonly === false) {
							set_password_fields_table_visibility(true);
						} else {
							set_password_fields_table_visibility(false);
						} // else
						break;
					case 'overwrite':
						prc_.mark_elemwidget_to_be_unhidden(
							widget_partialmenu_t1_retain_or_modify_);
						if (b_is_readonly === false) {
							var s_label1 = widget_partialmenu_t1_retain_or_modify_.get_content_s_label1();
							if (s_label1 === 'retain') {
								set_password_fields_table_visibility(false);
							} else {
								if (s_label1 === 'modify') {
									set_password_fields_table_visibility(true);
								} else {
									if (raudrohi_settings_debug_JavaScript) {
										throw raudrohi.tmg(
											'5ad107b5-37e1-4c78-895e-a09010703dd7',
											'There\'s no branching for s_label1(==' +
											s_label1 + ').');
									} // if
								} // else
							} // else
						} else { // b_is_readonly===true
							set_password_fields_table_visibility(false);
						} // else
						break;
					default:
						if (raudrohi_settings_debug_JavaScript) {
							throw raudrohi.tmg(
								'20384f31-4cc4-40a4-9e2e-a09010703dd7',
								'There\'s no branching for s_mode_(==' +
								s_mode_ + ').');
						} // if
				} // switch
			} catch (err) {
				raudrohi.tmg('f2645408-b5fc-4130-a79e-a09010703dd7', err);
			} // catch
		} // set_subwidgets_visibility_according_to_states
		//-----------------------------------------------------------------
		prc_.customizable.compulsory.render_editable = function() {
			try {
				create_containers();
				set_subwidgets_visibility_according_to_states();
			} catch (err) {
				raudrohi.tmg('4aea5d04-5af3-4bdf-9b4e-a09010703dd7', err);
			} // catch
		} // prc_.customizable.compulsory.render_editable


		prc_.customizable.compulsory.render_readonly = function() {
			try {
				create_containers();
				set_subwidgets_visibility_according_to_states();
			} catch (err) {
				raudrohi.tmg('44cfa72d-4a6f-4681-831e-a09010703dd7', err);
			} // catch
		} // prc_.customizable.compulsory.render_readonly

		//-----------------------------------------------------------------
		self_public_.private_code_.evh_.evh_partialmenu_t1_retain_or_modify_selected = function(mi) {
			try {
				set_subwidgets_visibility_according_to_states();
			} catch (err) {
				raudrohi.tmg('41720d33-b70b-4832-ae1d-a09010703dd7', err);
			} // catch
		} // self_public_.private_code_.evh_.evh_partialmenu_t1_retain_or_modify_selected
		//-----------------------------------------------------------------
		// Format described next to the
		// this.register_acceptance_verification_function
		var ar_acceptance_verification_functions_ = [];

		// The func_in is expected to return an array, where 
		// ar[0]==<boolean true for failure, otherwise false>
		// ar[1]==<empty string if no failure, otherwise password rejection message>
		this.register_acceptance_verification_function = function(func_in) {
			try {
				var i = 0;
				var x = null;
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isFunction(func_in, 'func_in',
						'e235ff9e-54cb-4299-8d5d-a09010703dd7');
					var s_err_msg = 'The registered password acceptance ' +
						'verification function does not meet the specification.';
					var ar_x = func_in('abra', 'cadabra');
					raudrohi.base.assert_isArray(ar_x, 'ar_x==func_in(...)',
						'021ddaab-1886-4ba7-9d4d-a09010703dd7', s_err_msg);
					i = ar_x.length;
					if (i != 2) {
						raudrohi.tmg('45611666-a1bb-439d-a4cd-a09010703dd7',
							s_err_msg +
							' 2 != (func_in(...)==ar_x).length == ' + i);
					} // if
					x = ar_x[0];
					raudrohi.base.assert_isBoolean(x, 'ar_x[0]',
						'04dd073d-15df-4c17-b32d-a09010703dd7', s_err_msg);
					x = ar_x[1];
					raudrohi.base.assert_isString(x, 'ar_x[1]',
						'5e3b0f42-a6f1-4bb8-aa1d-a09010703dd7', s_err_msg);
				} // if
				ar_acceptance_verification_functions_.push(func_in);
				if (b_acceptable_password_string_available_ === true) {
					// The new function might deem the
					// previously accepted password unacceptable.
					password_acceptance_verification();
				} // if
			} catch (err) {
				raudrohi.tmg('35490f52-14c4-43f9-932d-a09010703dd7', err);
			} // catch
		} // register_acceptance_verification_function

		function remove_all_acceptance_verification_functions_except_mismatch() {
			try {
				ar_acceptance_verification_functions_ = [];
				if (b_password_string_available_but_unacceptable_ === true) {
					// The password might have been deemed
					// unacceptable by one of the functions
					// that got unregistered here.
					password_acceptance_verification();
				} // if
			} catch (err) {
				raudrohi.tmg('1464d213-52b0-4b19-9d1d-a09010703dd7', err);
			} // catch
		} // remove_all_acceptance_verification_functions_except_mismatch

		function password_acceptance_verification_rejected_by_func(s_line_1, s_line_2) {
			try {
				var b_password_rejected = false;
				var i_len = ar_acceptance_verification_functions_.length;
				var i = 0;
				var func_verification;
				var ar = null;
				var s_1 = null;
				for (i = 0; i < i_len; i++) {
					func_verification = ar_acceptance_verification_functions_[i];
					ar = func_verification(s_line_1, s_line_2);
					if (ar[0] === true) {
						s_1 = ar[1];
						if (s_password_rejection_message_ !== s_1) {
							s_password_rejection_message_ = s_1;
							b_password_rejection_message_display_needs_to_be_updated_ = true;
						} // if
						b_password_rejected = true;
						b_acceptable_password_string_available_ = false;
						break;
					} // if
				} // for
				return b_password_rejected;
			} catch (err) {
				raudrohi.tmg('73cb5015-52cc-4a72-ad1d-a09010703dd7', err);
			} // catch
		} // password_acceptance_verification_rejected_by_func

		function password_acceptance_verification() {
			try {
				b_acceptable_password_string_available_ = false;
				b_password_string_available_but_unacceptable_ = false;
				var rgx = RegExp("[\\n]+$", "g");
				var s_lc_emptystring = "";
				var s_line_1 = widget_textarea_t1_line_1_.get_content().replace(
					rgx, s_lc_emptystring);
				var s_line_2 = widget_textarea_t1_line_2_.get_content().replace(
					rgx, s_lc_emptystring);
				if (s_line_1.length !== s_line_2.length) {
					if (s_password_rejection_message_ !== s_password_mismatch_message_) {
						s_password_rejection_message_ = s_password_mismatch_message_;
						b_password_rejection_message_display_needs_to_be_updated_ = true;
					} // if
					b_password_string_available_but_unacceptable_ = true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if
				if (s_line_1.length === 0) { // ===s_line_2.lenght
					s_password_rejection_message_ = "Password length==0."; // hidden anyway
					b_password_rejection_message_display_needs_to_be_updated_ = true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if
				if (s_line_1 !== s_line_2) {
					s_password_rejection_message_ = s_password_mismatch_message_;
					b_password_rejection_message_display_needs_to_be_updated_ = true;
					b_password_string_available_but_unacceptable_ = true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if

				if (password_acceptance_verification_rejected_by_func(s_line_1, s_line_2) === true) {
					b_password_string_available_but_unacceptable_ = true;
					prc_.repaint_if_graphical_and_not_hidden();
					return;
				} // if
				s_acceptable_password_string_ = s_line_1;
				b_acceptable_password_string_available_ = true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('21b141d2-654e-4160-8d9d-a09010703dd7', err);
			} // catch
		} // password_acceptance_verification


		//-----------------------------------------------------------------

		//wg_hooks_.evh_widget_textarea_t1_line_1_key_13=function(e) {
		// This function is meant to be overridden.
		//} // wg_hooks_.evh_widget_textarea_t1_line_2_key_13

		prc_.evh_.evh_widget_textarea_t1_line_1_key_blur_local = function(e) {
			try {
				var s_line_2 = widget_textarea_t1_line_2_.get_content();
				if (0 < s_line_2.length) {
					password_acceptance_verification();
				} // if
			} catch (err) {
				raudrohi.tmg('214fc34e-4240-41d9-983c-a09010703dd7', err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_1_key_blur_local

		prc_.evh_.evh_widget_textarea_t1_line_1_key_13_local = function(e) {
			try {
				var s_line_2 = widget_textarea_t1_line_2_.get_content();
				if (0 < s_line_2.length) {
					password_acceptance_verification();
				} // if
				widget_textarea_t1_line_2_.set_focus();
				//wg_hooks_.evh_widget_textarea_t1_line_1_key_13(e);
			} catch (err) {
				raudrohi.tmg('e48bf0c2-3b67-4899-a01c-a09010703dd7', err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_1_key_13_local

		wg_hooks_.evh_widget_textarea_t1_line_2_key_13 = function(e) {
			// This function is meant to be overridden.
		} // wg_hooks_.evh_widget_textarea_t1_line_2_key_13

		prc_.evh_.evh_widget_textarea_t1_line_2_key_blur_local = function(e) {
			try {
				password_acceptance_verification();
			} catch (err) {
				raudrohi.tmg('e6e76ae5-dc5d-41ac-882c-a09010703dd7', err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_2_key_blur_local

		prc_.evh_.evh_widget_textarea_t1_line_2_key_13_local = function(e) {
			try {
				password_acceptance_verification();
				wg_hooks_.evh_widget_textarea_t1_line_2_key_13(e);
			} catch (err) {
				raudrohi.tmg('74cad187-5322-4167-b619-a09010703dd7', err);
			} // catch
		} // prc_.evh_.evh_widget_textarea_t1_line_2_key_13_local


		//-----------------------------------------------------------------
		function initiate_widgets() {
			try {
				self_public_.set_line_1_legend('');
				self_public_.set_line_2_legend('');
				widget_partialmenu_t1_retain_or_modify_.private_code_.customizable.optional.evh_selection_impl = self_public_.private_code_.evh_.evh_partialmenu_t1_retain_or_modify_selected;
				// raudrohi_virtual_key_blur
				widget_textarea_t1_line_1_.set_keylistener('13',
					prc_.evh_.evh_widget_textarea_t1_line_1_key_13_local);
				widget_textarea_t1_line_2_.set_keylistener('13',
					prc_.evh_.evh_widget_textarea_t1_line_2_key_13_local);
				widget_textarea_t1_line_1_.set_keylistener(
					'raudrohi_virtual_key_blur',
					prc_.evh_.evh_widget_textarea_t1_line_1_key_blur_local);
				widget_textarea_t1_line_2_.set_keylistener(
					'raudrohi_virtual_key_blur',
					prc_.evh_.evh_widget_textarea_t1_line_2_key_blur_local);
				//self_public_.private_code_.evh_.evh_button_add_new_report=function(e){
			} catch (err) {
				raudrohi.tmg('452c1773-7c92-4634-9d18-a09010703dd7', err);
			} // catch
		} // initiate_widgets

		prc_.customizable.optional.create_subwidgets = function() {
			try {
				create_widgets_autogen();
				initiate_widgets();
			} catch (err) {
				raudrohi.tmg('25a3b473-8fee-4ff4-9f18-a09010703dd7', err);
			} // catch
		} // prc_.customizable.optional.create_subwidgets=function(){

		//-----------------------------------------------------------------
		var s_mode_ = 'add_new';
		this.set_mode = function(s_mode) {
			try {
				var i = null;
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isString(
						s_mode, 's_mode', '725d5e49-5cf4-4fc9-9b48-a09010703dd7');
					i = s_mode.length;
					raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(1,
						'1', 'e13c890f-880b-4ab0-b448-a09010703dd7',
						i, 's_mode.length', ' Empty strings are not allowed.');
					switch (s_mode) {
						case 'add_new':
							break;
						case 'overwrite':
							break;
						default:
							if (raudrohi_settings_debug_JavaScript) {
								throw raudrohi.tmg(
									'24a4ffe1-2eb3-4e68-9518-a09010703dd7',
									'There\'s no branching for s_mode(==' +
									s_mode + ').');
							} // if
					} // switch
				} // if
				if (s_mode_ === s_mode) {
					return;
				} // if
				s_mode_ = "" + s_mode;
				widget_partialmenu_t1_retain_or_modify_.set_content_by_s_label1(
					'modify');
				prc_.containers_html_cached_ = false;
				prc_.repaint_if_graphical_and_not_hidden();
				// The duplication of widget_partialmenu_t1_retain_or_modify_
				// selection assignment is just to increase fault tolerance,
				// because the menu position really has to be "modify",
				// if the s_mode==="add_new" and one can not be too sure,
				// what will happen at the graphical side before
				// this function exits. In theory, if the JavaScript
				// is really a single-threaded application, the
				// secondary menu content assignment is not necessary,
				// but this is the WEB, which tends to be
				// somewhat crappy, so I'll better be safe than sorry.
				widget_partialmenu_t1_retain_or_modify_.set_content_by_s_label1(
					'modify');
			} catch (err) {
				raudrohi.tmg('13e3338b-8fa4-41c6-ae38-a09010703dd7', err);
			} // catch
		} // set_mode

		this.s_get_mode = function() {
			try {
				var s_out = "" + s_mode_;
				return s_out;
			} catch (err) {
				raudrohi.tmg('6f5f5034-5c13-4b8f-b238-a09010703dd7', err);
			} // catch
		} // s_get_mode

		//-----------------------------------------------------------------
		var s_menu_position_ = 'north';

		// s_menu_position inSet {"north", "south", "east", "west"}
		// The position is relative to the textfields. For example,
		// If the menu is to the right of the visible textfields, then
		// the  s_menu_position=="west".
		this.set_menu_position = function(s_menu_position) {
			try {
				var i = null;
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isString(
						s_menu_position, 's_menu_position',
						'8155bc0f-84f8-4046-be58-a09010703dd7');
					i = s_menu_position.length;
					raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(1,
						'1', '444b298b-16f4-4310-8ca7-a09010703dd7',
						i, 's_menu_position.length',
						' Empty strings are not allowed.');
				} // if
				if (s_menu_position_ === s_menu_position) {
					return;
				} // if
				switch (s_menu_position) {
					case 'north':
						break;
					case 'south':
						break;
					case 'east':
						break;
					case 'west':
						break;
					default:
						if (raudrohi_settings_debug_JavaScript) {
							throw raudrohi.tmg(
								'3d8c4f74-8993-4832-ae47-a09010703dd7',
								'There\'s no branching for s_menu_position(==' +
								s_menu_position + ').');
						} // if
				} // switch
				s_menu_position_ = "" + s_menu_position;
				prc_.containers_html_cached_ = false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('b987ecc2-8a2e-4ebe-a217-a09010703dd7', err);
			} // catch
		} // set_menu_position

		this.s_get_menu_position = function() {
			try {
				var s_out = "" + s_menu_position_;
				return s_out;
			} catch (err) {
				raudrohi.tmg('1c5dde24-4917-4951-be57-a09010703dd7', err);
			} // catch
		} // s_get_menu_position

		//-----------------------------------------------------------------
		var i_password_field_width_ = 20;
		this.set_i_password_field_width = function(i_password_field_width) {
			try {
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isNumber(
						i_password_field_width, 'i_password_field_width',
						'5949f0c0-2855-4eed-83c7-a09010703dd7');
					raudrohi.lang.assert_is_a_whole_number(
						i_password_field_width, 'i_password_field_width',
						'9c45f599-7a58-4c10-9827-a09010703dd7');
					raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(5,
						'5', '43035331-0d5a-4320-8b37-a09010703dd7',
						i_password_field_width, 'i_password_field_width', '');
				} // if
				if (i_password_field_width_ === i_password_field_width) {
					return;
				} // if
				i_password_field_width_ = "" + i_password_field_width;
				b_password_rejection_message_display_needs_to_be_updated_ = true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('3f710fd4-4d21-4eff-bb17-a09010703dd7', err);
			} // catch
		} // set_i_password_field_width

		this.s_get_i_password_field_width = function() {
			try {
				var i_out = 0 + i_password_field_width_;
				return i_out;
			} catch (err) {
				raudrohi.tmg('853427b7-0a17-461e-9346-a09010703dd7', err);
			} // catch
		} // s_get_i_password_field_width

		//-----------------------------------------------------------------
		var i_password_field_legend_width_ = 15;
		this.set_i_password_field_legend_width = function(i_password_field_legend_width) {
			try {
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isNumber(
						i_password_field_legend_width, 'i_password_field_legend_width',
						'63d7d1be-5756-4623-9d36-a09010703dd7');
					raudrohi.lang.assert_is_a_whole_number(
						i_password_field_legend_width, 'i_password_field_legend_width',
						'2ed76181-b3a3-44ea-8036-a09010703dd7');
					raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(5,
						'5', 'd2540ed4-d25a-4327-8146-a09010703dd7',
						i_password_field_legend_width, 'i_password_field_legend_width', '');
				} // if
				if (i_password_field_legend_width_ === i_password_field_legend_width) {
					return;
				} // if
				i_password_field_legend_width_ = "" + i_password_field_legend_width;
				prc_.containers_html_cached_ = false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('544bf384-2bfe-4bfb-9456-a09010703dd7', err);
			} // catch
		} // set_i_password_field_legend_width

		this.s_get_i_password_field_legend_width = function() {
			try {
				var i_out = 0 + i_password_field_legend_width_;
				return i_out;
			} catch (err) {
				raudrohi.tmg('433cb424-92e3-4792-af56-a09010703dd7', err);
			} // catch
		} // s_get_i_password_field_legend_width

		//-----------------------------------------------------------------
		var s_line_1_legend_ = 'not_set';
		this.set_line_1_legend = function(s_line_1_legend) {
			try {
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isString(
						s_line_1_legend, 's_line_1_legend',
						'fb2277e4-1198-4b10-bdd6-a09010703dd7');
				} // if
				if (s_line_1_legend_ === s_line_1_legend) {
					return;
				} // if
				s_line_1_legend_ = "" + s_line_1_legend;
				var s_wdwpd = raudrohi.lang.word_wrap(s_line_1_legend_,
					i_password_field_legend_width_, "<br/>\n", ' ');
				widget_html_t2_line_1_legend_.set_content(s_wdwpd);
				prc_.containers_html_cached_ = false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('871e6ec3-d7e0-447f-8065-a09010703dd7', err);
			} // catch
		} // set_line_1_legend

		this.s_get_line_1_legend = function() {
			try {
				var s_out = "" + s_line_1_legend_;
				return s_out;
			} catch (err) {
				raudrohi.tmg('955bfbc9-fbcf-4453-98a5-a09010703dd7', err);
			} // catch
		} // s_get_line_1_legend

		//-----------------------------------------------------------------
		var s_line_2_legend_ = 'not_set';
		this.set_line_2_legend = function(s_line_2_legend) {
			try {
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isString(
						s_line_2_legend, 's_line_2_legend',
						'1fa24423-6840-4151-8e35-a09010703dd7');
				} // if
				if (s_line_2_legend_ === s_line_2_legend) {
					return;
				} // if
				s_line_2_legend_ = "" + s_line_2_legend;
				var s_wdwpd = raudrohi.lang.word_wrap(s_line_2_legend_,
					i_password_field_legend_width_, "<br/>\n", ' ');
				widget_html_t2_line_2_legend_.set_content(s_wdwpd);
				prc_.containers_html_cached_ = false;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('42d13b23-33c1-4d7f-8e45-a09010703dd7', err);
			} // catch
		} // set_line_2_legend

		this.s_get_line_2_legend = function() {
			try {
				var s_out = "" + s_line_2_legend_;
				return s_out;
			} catch (err) {
				raudrohi.tmg('61baaad8-1cee-4380-98f5-a09010703dd7', err);
			} // catch
		} // s_get_line_2_legend

		//-----------------------------------------------------------------
		var s_password_mismatch_message_ = "The passowords don't match.";
		this.set_password_mismatch_message = function(s_password_mismatch_message) {
			try {
				var i = null;
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isString(
						s_password_mismatch_message, 's_password_mismatch_message',
						'2d6ebcf1-660f-4613-8735-a09010703dd7');
					i = s_password_mismatch_message.length;
					raudrohi.base.assert_X1_isSmallerThanOrEqualTo_X2(1,
						'1', '5f6536e3-a712-49b1-b355-a09010703dd7',
						i, 's_password_mismatch_message.length',
						' Empty strings are not allowed.');
				} // if
				if (s_password_mismatch_message_ === s_password_mismatch_message) {
					return;
				} // if
				s_password_mismatch_message_ = "" + s_password_mismatch_message;
				b_password_rejection_message_display_needs_to_be_updated_ = true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('43e33901-fcd2-4083-8634-a09010703dd7', err);
			} // catch
		} // set_password_mismatch_message

		this.s_get_password_mismatch_message = function() {
			try {
				var s_out = "" + s_password_mismatch_message_;
				return s_out;
			} catch (err) {
				raudrohi.tmg('aa06c45f-392e-49cf-8714-a09010703dd7', err);
			} // catch
		} // s_get_password_mismatch_message

		//-----------------------------------------------------------------
		var s_password_rejection_message_color_ = window.raudrohi.widgets.g1.theme.s_color_no;
		this.set_password_rejection_message_color = function(
			s_password_rejection_message_color) {
			try {
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isString(
						s_password_rejection_message_color,
						's_password_rejection_message_color',
						'3f368c93-13a7-4c0e-b414-a09010703dd7');
					raudrohi.lang.assert_is_an_HTML_color(
						s_password_rejection_message_color,
						's_password_rejection_message_color',
						'39f174c5-edf5-42f8-8e44-a09010703dd7');
				} // if
				if (s_password_rejection_message_color_ === s_password_rejection_message_color) {
					return;
				} // if
				s_password_rejection_message_color_ = "" + s_password_rejection_message_color;
				b_password_rejection_message_display_needs_to_be_updated_ = true;
				prc_.repaint_if_graphical_and_not_hidden();
			} catch (err) {
				raudrohi.tmg('f332eac7-a803-4b55-8454-a09010703dd7', err);
			} // catch
		} // set_password_rejection_message_color

		this.s_get_password_rejection_message_color = function() {
			try {
				var s_out = "" + s_password_rejection_message_color_;
				return s_out;
			} catch (err) {
				raudrohi.tmg('31385074-2af5-477a-9d44-a09010703dd7', err);
			} // catch
		} // s_get_password_rejection_message_color

		//-----------------------------------------------------------------
		// Retunrs an instance namespace x with a format of:
		//
		// x.b_password_not_available
		// x.s_password
		// x.b_retain_old_password
		//
		// if(x.b_password_not_available===true){ x.s_password==='';}
		// if(x.b_retain_old_password===true){ x.b_password_not_available===true;}
		this.get_content = function() {
			try {
				var x_out = {};
				x_out.s_password = '';
				x_out.b_password_not_available = true;
				var s_label1 = widget_partialmenu_t1_retain_or_modify_.get_content_s_label1();
				if (s_label1 === 'retain') {
					x_out.b_retain_old_password = true;
					return x_out;
				} // if
				x_out.b_retain_old_password = false; // s_label1==='modify'
				password_acceptance_verification();
				if (b_acceptable_password_string_available_ === true) {
					x_out.s_password = '' + s_acceptable_password_string_;
					x_out.b_password_not_available = false;
				} // if
				return x_out;
			} catch (err) {
				raudrohi.tmg('d083d642-ec4b-4437-9034-a09010703dd7', err);
			} // catch
		} // get_content

		//-----------------------------------------------------------------
		this.get_content_2_collection_t1 = function(ht) {
			try {
				if (raudrohi_settings_debug_JavaScript === true) {
					raudrohi.base.assert_isObject(ht, 'ht',
						'511a1dc5-3b0a-4519-8f13-a09010703dd7');
				} // if
				var s_sb_set = raudrohi.wg_processing_t1.s_key_field_set(
					self_public_);
				var s_dbf_key = raudrohi.wg_processing_t1.s_key_field(
					self_public_);
				var x = self_public_.get_content();
				if (x.b_retain_old_password === true) {
					ht.put(s_dbf_key, ' ');
					ht.put(s_sb_set, 'f');
					return;
				} // if
				if (x.b_password_not_available === true) {
					raudrohi.tmg('120cfa71-81b6-462d-a923-a09010703dd7',
						'self_public_.get_content().b_retain_old_password===false and ' +
						'self_public_.get_content().b_password_not_available===true , but' +
						'the self_public_.get_content_2_collection_t1(...) got called. ' +
						'The parent widget is expected to verify that the ' +
						'self_public_.get_content().b_password_not_available===false ' +
						'before calling the self_public_.get_content_2_collection_t1(...)' +
						'');
				} // if
				ht.put(s_dbf_key, x.s_password);
				ht.put(s_sb_set, 't');
			} catch (err) {
				raudrohi.tmg('45aa6763-549c-43ba-b913-a09010703dd7', err);
			} // catch
		} // get_content_2_collection_t1

		this.set_content_from_collection_t1 = function(ht) {
			try {
				// Passwords are never expected to be sent from the
				// server.
				self_public_.set_mode('overwrite');
				widget_partialmenu_t1_retain_or_modify_.set_content_by_s_label1(
					'retain');
			} catch (err) {
				raudrohi.tmg('15c901a2-e9ff-4354-ab23-a09010703dd7', err);
			} // catch
		} // set_content_from_collection_t1

		//-----------------------------------------------------------------
		prc_.customizable.optional.startup_hook = function() {
			try {
				// This function can be deleted from here, because
				// it is already defined in the pile of methods.
			} catch (err) {
				raudrohi.tmg('f25495b2-d795-48fb-b523-a09010703dd7', err);
			} // catch
		} // prc_.customizable.optional.startup_hook

		prc_.customizable.optional.shutdown_hook = function() {
			try {
				// This function can be deleted from here, because
				// it is already defined in the pile of methods.
			} catch (err) {
				raudrohi.tmg('056f8685-132a-41de-b7b3-a09010703dd7', err);
			} // catch
		} // prc_.customizable.optional.shutdown_hook

		self_public_.startup_sequence_init();
	} catch (err) {
		raudrohi.tmg('185ed973-53dc-4970-9642-a09010703dd7', err);
	} // catch
} // raudrohi.widgets.g1.password_editor_t1

//-------------------------------------------------------------------------
